### ISSUE TITLE
Relationship Connection only working at top-level

### ISSUE THREAD

**Issue by danielfein** [neo4j/graphql#613] opened 2021-11-26 20:33 UTC
**Describe the bug**
Hi I'm not sure if this is expected or not, as I can see Aggregation methods are only available top-level but I'm trying to fetch properties of a relationship at a lower level/nested query.

Relevant type definitions:
```
type Quote { 
    id: ID! @id(autogenerate: true),
    text: String!
}

type Post {
    id: ID! @id(autogenerate: true),
    body: String,
    quotes: [Quote] @relationship(type: "HAS_QUOTE", properties: "QuotePost", direction: OUT),
}

type User {
    id: ID! @id(autogenerate: true)
    posts: [Post] @relationship(type: "WROTE", direction: OUT),

interface QuotePost {
    date_added: DateTime,
    format: String
}
```

so `User`s can write `Post`s which can have `Quote`s which have, per connection to posts, specific properties.

I can grab the quotes like this:
```
users {
   posts {
     quotes {
         text
     }
   }
}
```

and I can grab the quotesConnections at top-level, like:

```
   posts {
         quotesConnection {
         edges {
             format
             etc...
          }
     }
   }
```

but I want to grab the connection data when looking at posts specific to users but can't, I'd like to do this:

```
users {
   posts {
     quotesConnection {
         edges {
             format
             etc...
          }
     }
   }
}
```

Is this supposed to be available? Is it limited to top-level only?

**Comment by dmoree** [comment] 2021-11-26 22:14
@danielfein What version of `@neo4j/graphql` are you using? I think nested aggregations are available in `2.4.0`

**Comment by danielfein** [comment] 2021-11-29 19:09
Hi @dmoree - I'm currently using `2.4.0` with the below issue.

**Comment by angrykoala** [comment] 2021-11-30 16:47
Hi @danielfein 
Could you add the error you are getting please?
This should work in `2.4.0` and I'm not able to reproduce the issue

**Comment by danielfein** [comment] 2021-12-01 06:48
Hi @angrykoala I just tried it again to narrow down the issue, it looks like the issue arises with `DateTime` types. Here's the error I receive:

     ``` "message": "Invalid input 'iso_zoned_date_time': expected\n  \"!=\"\n  \"%\"\n  \")\"\n  \"*\"\n  \"+\"\n  \",\"\n  \"-\"\n  \".\"\n  \"/\"\n  \":\"\n  \"<\"\n  \"<=\"\n  \"<>\"\n  \"=\"\n  \"=~\"\n  \">\"\n  \">=\"\n  \"AND\"\n  \"CONTAINS\"\n  \"ENDS\"\n  \"IN\"\n  \"IS\"\n  \"OR\"\n  \"STARTS\"\n  \"XOR\"\n  \"[\"\n  \"^\" (line 7, column 173 (offset: 592))\n\"WITH collect({ isActive: this_details_has_detail_relationship.isActive, date_updated: apoc.date.convertFormat(toString(this_details_has_detail_relationship.date_updated), \"iso_zoned_date_time\", \"iso_offset_date_time\") }) AS edges\"\n   ```

Thanks!

**Comment by darrellwarde** [comment] 2021-12-01 08:51
@danielfein, this _should_ be fixed in our next release. See #587. 🙂

**Comment by angrykoala** [comment] 2021-12-02 16:48
As @darrellwarde mentioned, this seems to be fixed now. I'll close this issue, if you are still seeing this problem, please feel free to comment here @danielfein

**Closed by angrykoala** 2021-12-02 16:48 UTC
Labels: inbox, bug report
