### ISSUE TITLE
Constraints violations do not provide helpful errors

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3499] opened 2023-06-15 11:57 UTC
Currently a message "constraint failed" or similar is produced. It would be useful to show the name of the constraint or similar.

**Comment by neo4j-team-graphql** [comment] 2023-06-15 11:57
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by jroith** [comment] 2023-06-16 09:09
If someone submits a mutation and it fails due to a unique constraint, the cause should be exposed also in production. I would even argue that a structured error should be returned. Especially since this "secret" can be trivially detected by an attacker by just repeatedly changing the values of the submitted fields. If this would be secret information it should be handled using the existing auth mechanisms or by making it possible to declare if a unique constraint is in fact secret or not.

**Comment by darrellwarde** [comment] 2023-06-16 09:21
@jroith, it is our job to build a library that works in _all_ situations. Whilst a user may not have an issue with raising detailed errors in production for perhaps an internal application, our view is that this wouldn't be so desirable for a public API. Whilst I 100% agree that our error messages need to be massively improved, we want to avoid situations where our error messages could leak details of the database underlying the API, or information on data that exists in the database.

**Comment by jroith** [comment] 2023-06-16 09:52
I understand, which is why I think it could be helpful to add a parameter to the @unique directive.

**Comment by to-kn** [comment] 2023-06-19 10:34
@darrellwarde i have a question, since we are running in the same error/problem.
On the frontend i need to know which field missed validation, eg. which field value needs to be unique. Since i have currently no possibility to pass the desired info to the frontend (even with a try/catch arount ogm.model.create/update i do not get more details to the error) i am stuck with implementing a iteration over all existing values to "guess" the right field in front and backend...
What is the recommended way of doing this?

**Comment by darrellwarde** [comment] 2024-02-21 15:12
Closing as duplicate of #2514.

**Closed by darrellwarde** 2024-02-21 15:12 UTC
Labels: feature request
