### ISSUE TITLE
Authorization rules can't compare enum property with context

### ISSUE THREAD

**Issue by jbhurruth** [neo4j/graphql#5126] opened 2024-05-14 10:30 UTC
**Describe the bug**
We have a requirement to check that a node's enum property in a list of enum values that we provide in the context object. When attempting something like the following schema definition we get the error `Invalid argument: filter, error: Value \"$context.enum_list\" does not exist in \"Choice\" enum.`

Is this a bug or is there another sneaky way to achieve this?

**Type definitions**
```graphql
  enum Choice {
    A
    B
    C
  }
  type Example @authorization(
    filter: [{
      where: { node: { enum_IN: "$context.enum_list"} }
    }]
  ) {
    enum: Choice!
  }
```

**To Reproduce**

1. Run a server with the above scheme
2. See error on schema validation

**Expected behavior**
I would expect the validation to ignore scenarios like this since there's no way at validation time that the types could be checked.

**System (please complete the following information):**

* OS: macOS Sonoma
* Version: @neo4j/graphql@5.3.6
* Node.js version: v21.4.0

**Additional context**
We're already trying to work around the inability to compare two node properties across multiple connections in an authorization rule.

**Comment by neo4j-team-graphql** [comment] 2024-05-14 10:30
Many thanks for raising this bug report @jbhurruth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment] 2024-05-14 12:11
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @jbhurruth! :pray: We will now prioritise the bug and address it appropriately.

**Comment by angrykoala** [comment] 2024-05-21 12:31
Hi @jbhurruth 

Until this is fixed on our side, you should be able to use a string instead of an enum as a workaround

**Comment by darrellwarde** [comment] 2024-11-19 13:35
Closing as a duplicate of #2215 - any progress on this will be tracked there.

**Closed as not planned by darrellwarde** 2024-11-19 13:35 UTC
Labels: confirmed, bug
