### ISSUE TITLE
Unable to connect two nodes more than once

### ISSUE THREAD

**Issue by zen-alex-wilmer** [neo4j/graphql#4458] opened 2023-12-27 00:37 UTC
**Describe the bug**

I really apologize, I honestly can't tell if this is a bug or if I'm requesting a feature. Neo4j allows two nodes to have multiple edges between them, with or without differing relationship properties.

<img width="518" alt="image" src="https://github.com/neo4j/graphql/assets/143416753/d8ea5fc2-0f8f-42a6-99bf-d4baf8a1c66b">

Per the description in this PR https://github.com/neo4j/graphql/pull/2588 - the default behaviour when adding a new edge is to update the existing one, and when `overwrite` is set to `false` it errors instead of adding the additional edge. 

Am I doing something wrong? Is this a bug? Am I requesting a feature?.

**Type definitions**

```
type Flow {
  name: String!
  sections: [Section!]! @relationship(type: "CONTAINS", properties: "Meta", direction: OUT)
}

type Section {
  name: String!
  flows: [Flow!]! @relationship(type: "CONTAINS", properties: "Meta", direction: IN)
}

interface Meta @relationshipProperties {
  id: String!
}
```

**To Reproduce**

1. Run a server with the following code...

```
import { ApolloServer } from "@apollo/server";
import { startStandaloneServer } from "@apollo/server/standalone";
import { Neo4jGraphQL } from "@neo4j/graphql";
import neo4j from "neo4j-driver";
import dotenv from "dotenv";
import { typeDefs } from "./typeDefs.js";

dotenv.config();

const driver = neo4j.driver(
  process.env.N4J_URI,
  neo4j.auth.basic(process.env.N4J_USER, process.env.N4J_PASSWORD)
);

const neoSchema = new Neo4jGraphQL({ typeDefs, driver });

const server = new ApolloServer({
  schema: await neoSchema.getSchema(),
});

const { url } = await startStandaloneServer(server, {
  context: async ({ req }) => ({ req }),
  listen: { port: 4000 },
});

console.log(`🚀 Server ready at ${url}`);
```

2. Execute the following Mutation...

- create one flow
- create one section
- connect the flow to the section with `edge { id: 1 }`
- connect the flow to the section with `edge { id: 2 }`, 
  - results in the first edge being overwritten as expected
- connect the flow to the section with `edge { id: 3 }, overwrite: false`
  - throws an error, which makes sense given the above PR, but then how is one supposed to add multiple connections between two nodes?

**Expected behavior**
`overwrite: false` should not throw, it should prevent overwriting 

**System (please complete the following information):**

* OS: macOS
* Version: `@neo4j/graphql": "^4.4.4"`
* Node.js version: `v21.1.0`

**Additional context**

I asked in the discord #graphql channel, but it is the holidays. Hopefully everyone's cool with me creating this issue, if not let me know.

I'm happy to make PR for this, if this indeed a bug fix / feature that's needed.

**Comment by neo4j-team-graphql** [comment] 2023-12-27 00:37
Many thanks for raising this bug report @zen-alex-wilmer. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment] 2024-01-09 10:10
Hey @zen-alex-wilmer, sorry for the slow reply on this one and the quiet on Discord over the holiday period!

Of course, we love seeing issues like this! This is more of a feature request than a bug, so I will change the labels.

I'm afraid this won't be as simple as just a PR for this functionality - I think it's one of those features that we need to have some big discussions about in the team about how we allow all of the different "options" for connections, including this one, in an easy to use API.

**Comment by zen-alex-wilmer** [comment] 2024-01-09 15:26
Thanks @darrellwarde. Thankfully writing a custom resolver for this was very easy. I'm happy to participate in discussions about the API, let me know if you need my help.

**Comment by darrellwarde** [comment] 2024-02-21 15:57
This appears to be a duplicate of #3279.

**Closed by darrellwarde** 2024-02-21 15:57 UTC
Labels: feature request

**Comment by zen-alex-wilmer** [comment] 2024-02-21 23:07
Oh great thanks - gonna drop in my custom resolver here in case it helps before you close.

```
async duplicateChangesetEdges(
      _parent,
      { baseChangesetId, targetChangesetId },
      context,
    ) {
      const session = context.driver.session()
      try {
        const result = await session.run(
          `
MATCH (a)-[oldRel:CONTAINS {changesetId: $baseId}]->(b)
WITH a,oldRel,b
CREATE (a)-[newRel:CONTAINS {changesetId: $newId}]->(b)
SET newRel.order = oldRel.order,
    newRel.base = oldRel.base
RETURN count(*) AS relationshipsCreated;
`,
          {
            baseId: baseChangesetId,
            newId: targetChangesetId,
          },
        )
        return "Success!"
      } catch (error) {
        throw new Error(error)
      } finally {
        await session.close()
      }
    },
```
