### ISSUE TITLE
Add default sort option to queryOptions directive

### ISSUE THREAD

**Issue by AnsonHwang86** [neo4j/graphql#1363] opened 2022-05-06 00:17 UTC
**Is your feature request related to a problem? Please describe.**
@queryOptions description in document
```@queryOptions
The @queryOptions is to be used on nodes, where applied will inject values into a query such as the limit.

"""The @queryOptions is to be used on nodes, where applied will inject values into a query such as the limit."""
directive @queryOptions(
    """If no limit argument is supplied on query will fallback to this value."""
    limit: {
        default: Int
        max: Int
    }
) on OBJECT
```

**Describe the solution you'd like**

add the sort option to it

```directive @queryOptions(
    limit: {
        default: Int
        max: Int
    }
    sort: [{
       filed1: ASC
   }
   {
       field2: DESC
   }]
) on OBJECT
```
**Describe alternatives you've considered**
   we also can achieve this by add @defaultSort directive as discussed in https://github.com/neo4j/graphql/issues/1261
**Additional context**

**Comment by darrellwarde** [comment] 2022-09-23 09:23
Hey, closing as a duplicate of #499. Thanks!

**Closed by darrellwarde** 2022-09-23 09:23 UTC
Labels: feature request
