### ISSUE TITLE
OGM Neo.ClientError.Statement.SyntaxError " WHERE var1 = true"

### ISSUE THREAD

**Issue by mikaelmattsson** [neo4j/graphql#2753] opened 2023-01-18 15:15 UTC
After upgrading from 3.6 to 3.14 this where-cause in one of our queries stops working.

My data looks like this. (:PartUsage)-[:USAGE_OF]->(:Part)-[:ASSEMBLED_BY]->(:Part)

```graphql
  partUsages(
    where: {
      part: {assembledByAggregate: {count_GT: 0}}
    }
  ) {
  # ...
```

This causes the query to look like this

```cypher
RUN MATCH (this:`PartUsage`)
 WHERE (EXISTS {
    MATCH (this)-[:USAGE_OF]->(this0:`Part`)
    WHERE var1 = true
}
```

Which results in an error like this:
```Variable `var1` not defined (line 4, column 11 (offset: 96)) " WHERE var1 = true" ^```

Changing 0 to something larger causes the same error.

this works fine:
```graphql
  partUsages(
    where: {
      part: {name: "test"}
    }
  ) {
  # ...
```

and so does this:
```graphql
  parts(
    where: {
      assembledByAggregate: {count_GT: 0}
    }
  ) {
  # ...
```

So it only seems having multiple levels in the where clause.

**System:**

* Version: @neo4j/graphql-ogm@3.14.2

**Comment by neo4j-team-graphql** [comment] 2023-01-18 15:15
Many thanks for raising this bug report @mikaelmattsson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment] 2023-01-18 15:15
Many thanks for raising this bug report @mikaelmattsson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by Liam-Doodson** [comment] 2023-01-18 16:28
Hi @mikaelmattsson! This looks as though it is caused by #2708 so I am going to close this issue as a duplicate. Please feel free to track the progress of that issue and re-open this if that does not fix your issue

**Closed by Liam-Doodson** 2023-01-18 16:28 UTC
Labels: bug report
