### ISSUE TITLE
In `@auth`, `allowUnauthenticated` rule is ignored when other role-based rules are present.

### ISSUE THREAD

**Issue by dominusmi** [neo4j/graphql#2548] opened 2022-12-12 14:33 UTC
**Describe the bug**
When using an object auth, the allowUnauthenticated rule is ignored if other role-based rules are present, e.g.
```
@auth(rules: [
    { operations: [READ], allow unauthenticated: true, where: {isPublic: true}}
    { operations: [READ], roles: ["ADMIN"]}
])
```
The first rule is ignored.

**Type definitions**
```
type User
@auth(rules: [
    { operations: [READ], allowUnauthenticated: true, where: {isPublic: true}}
    { operations: [READ], roles: ["ADMIN"]}
])
{
  userId: ID! @id
  isPublic: Boolean
}
```

**To Reproduce**
1. Create the above schema and create a few users, some with `isPublic=true` 
2. An unauthenticated select should return the users with `isPublic=true`, instead we get an `Unautheticated` error thrown

**Additional context**
This is due to an exception being raised when the second rule is checked, completely ignoring that the first rule allows it.

**Comment by neo4j-team-graphql** [comment] 2022-12-12 14:33
Many thanks for raising this bug report @dominusmi. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment] 2022-12-13 16:16
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @dominusmi! :pray: We will now prioritise the bug and address it appropriately.

**Comment by Liam-Doodson** [comment] 2022-12-13 16:19
Recreated with the following data:

```cypher
CREATE (:User { userId: "1", isPublic: true })
CREATE (:User { userId: "2", isPublic: false })
```

And query (while unauthenticated):

```graphql
query Query {
  users {
    userId
  }
}
```

**Comment by dominusmi** [comment] 2022-12-13 16:41
A bit more info, since I made the issue I actually gave a look at the code. What seems to happen is that the "role" predicate is applied to the whole query instead of only to the second part. But it seems to me like the way it's made is going to be very hard to disconnect them.

As a headstart, I created this test while I was debugging, which I added to `packages/graphql/tests/integration/directives/auth/allow-unauthenticated.int.test.ts`:
```typescript
describe("allowUnauthenticated with role-based rule", () => {
        test("should return a Post without errors", async () => {
            const typeDefs = `
                type ${Post} {
                    id: ID!
                    published: Boolean!
                }

                extend type ${Post} @auth(rules: [
                    { operations: [READ], allowUnauthenticated: true, where: {published: true} }
                    { operations: [READ], roles: ["ADMIN"], where: {} }
                ])
            `;

            const publicPostId = generate({ charset: "alphabetic" });
            const privatePostId = generate({ charset: "alphabetic" });

            const query = `
                {
                    ${Post.plural} {
                        id
                    }
                }
            `;

            const session = await neo4j.getSession();
            const neoSchema = new Neo4jGraphQL({
                typeDefs,
                plugins: {
                    auth: new Neo4jGraphQLAuthJWTPlugin({
                        secret: "secret",
                    }),
                },
            });

            await session.run(`
                CREATE (:${Post} {id: "${publicPostId}", published: true})
            `);

            await session.run(`
                CREATE (:${Post} {id: "${privatePostId}", published: false})
            `);

            const socket = new Socket({ readable: true });
            const req = new IncomingMessage(socket);

            const gqlResult = await graphql({
                contextValue: neo4j.getContextValuesWithBookmarks(session.lastBookmark(), { req }),
                schema: await neoSchema.getSchema(),
                source: query,
            });

            // Check that no errors have been throwed
            expect(gqlResult.errors).toBeUndefined();

            // Check if returned data is what we really want
            expect((gqlResult.data as any)?.[Post.plural]?.[0]?.id).toBe(publicPostId);
            expect((gqlResult.data as any)?.[Post.plural]?.length).toBe(1);
        });
    });
```
The issue I mentioned seems to be in this area:
https://github.com/neo4j/graphql/blob/728b53c82937602ca14df331953b85f83b66f0ab/packages/graphql/src/translate/translate-read.ts#L86

An example of the query generated:
```sql
MATCH (this:`ERsRAGkoPost`)
WHERE (
	(
		(this.published IS NOT NULL AND this.published = $auth_param0) 
		OR 
		any(auth_var1 IN ["ADMIN"] WHERE any(auth_var0 IN $auth.roles WHERE 	auth_var0 = auth_var1))
	) 
	AND 
	apoc.util.validatePredicate(
		NOT (any(var1 IN ["ADMIN"] WHERE any(var0 IN $auth.roles WHERE var0 = var1))), "@neo4j/graphql/FORBIDDEN", [0]
	)
)
```

**Comment by Liam-Doodson** [comment] 2022-12-16 16:11
Hi @dominusmi! As you say, this is due to how role predicates are applied and it won't be easy to fix this without breaking roles authentication.

We're going to be making changes to the `@auth` directive in Q1 2023 that will be released in version 4.0.0 of the library. We will aim to address this issue as part of those changes.

If you want to try these changes out early, keep an eye out for beta releases of version 4.0.0.

**Comment by dominusmi** [comment] 2022-12-20 14:50
Excited about the new version!

**Comment by flchaux** [comment] 2023-02-21 13:29
Hi, does it mean it's not possible to use allowUnauthenticated and roles for the same entity? Is there any workaround until this issue is solved?

**Comment by darrellwarde** [comment] 2023-07-06 13:11
Hey @dominusmi, @flchaux, apologies that it's been a little while, but this should now be resolved with the release of the new authorization features in 3.23.0!

I would really encourage you to [migrate](https://neo4j.com/docs/graphql-manual/current/guides/v4-migration/authorization/), we would love your feedback!

I have raised a PR #3606 which adds an integration test demonstrating that this works in practice, please take a look at the code.

I'll close this for now, if you have any issues with the new features, then please raise another issue!

**Closed by darrellwarde** 2023-07-06 13:11 UTC
Labels: confirmed, bug report
