### ISSUE TITLE
Bug: Sort fails if field is not selected

### ISSUE THREAD

**Issue by dmoree** [neo4j/graphql#780] opened 2022-01-12 06:35 UTC
#### Describe the bug
When sorting on a node if the field is not in the selection set then the sort fails. See additional context for debugger statements, but the error is coming from the fact that the sort is ultimately on a map that is generated from the projection in the case of top level queries or in an `apoc.coll.sortMulti` in the case of nested relationships.

The solution seems to be looking at the `options` argument and manually adding the fields to the fields in the selection set.

#### Type definitions
Based on `neo-push` example
#### To Reproduce

1. Clone repository
```
git@github.com:dmoree/neo4j-graphql-issue-sort-on-missing-fields.git
```
2. Seed and start server
```
cd neo4j-graphql-issue-sort-on-missing-fields && yarn install && yarn seed && yarn start
```
3. Run the queries in GraphiQL at `http://localhost:4001/graphql` (or as defined in `.env`)

###### Query

```graphql
query SortOnTopLevelWithFieldSelected {
  blogs(options: {sort: {name: DESC}}) {
    id
    name
  }
}
```

###### Response
```
{
  "data": {
    "blogs": [
      {
        "id": "2",
        "name": "b"
      },
      {
        "id": "1",
        "name": "a"
      }
    ]
  }
}
```

###### Query

```graphql
query SortOnTopLevelWithFieldNotSelected {
  blogs(options: {sort: {name: DESC}}) {
    id
  }
}
```

###### Response
```
{
  "data": {
    "blogs": [
      {
        "id": "1"
      },
      {
        "id": "2"
      }
    ]
  }
}
```

###### Query

```graphql
query SortOnNestedLevelWithFieldSelected {
  blogs(where: {id:1}) {
    id
    posts(options: {sort: {title: ASC}}) {
      id
      title
    }
  }
}
```

###### Response
```
{
  "data": {
    "blogs": [
      {
        "id": "1",
        "posts": [
          {
            "id": "3",
            "title": "d"
          },
          {
            "id": "4",
            "title": "e"
          }
        ]
      }
    ]
  }
}
```

###### Query

```graphql
query SortOnNestedLevelWithFieldNotSelected {
  blogs(where: {id:1}) {
    id
    posts(options: {sort: {title: ASC}}) {
      id
    }
  }
}
```

###### Response
```
{
  "data": {
    "blogs": [
      {
        "id": "1",
        "posts": [
          {
            "id": "4"
          },
          {
            "id": "3"
          }
        ]
      }
    ]
  }
}
```

#### Expected Behavior
To be able to sort nodes without having to select field.

#### System (please complete the following information):

-   Version: @neo4j/graphql@2.5.5
-   Node.js version: 14.16.0

###### Top Level
```
@neo4j/graphql:graphql Incoming GraphQL:
Query:
query SortOnTopLevelWithFieldNotSelected {
  blogs(options: {sort: {name: DESC}}) {
    id
  }
}
Variables:
{} +7m
  @neo4j/graphql:auth Could not get .authorization, .Authorization or .cookies.token from req +7m
  @neo4j/graphql:execute About to execute Cypher:
Cypher:
MATCH (this:Blog)
RETURN this { .id } as this
ORDER BY this.name DESC
Params:
{} +7m
  @neo4j/graphql:execute Execute successful, received 2 records +7ms
```
###### Nested Level
```
@neo4j/graphql:graphql Incoming GraphQL:
Query:
query SortOnNestedLevelWithFieldNotSelected {
  blogs(where: {id: 1}) {
    id
    posts(options: {sort: {title: ASC}}) {
      id
    }
  }
}
Variables:
{} +1m
  @neo4j/graphql:auth Could not get .authorization, .Authorization or .cookies.token from req +1m
  @neo4j/graphql:execute About to execute Cypher:
Cypher:
MATCH (this:Blog)
WHERE this.id = $this_id
RETURN this { .id, posts: apoc.coll.sortMulti([ (this)-[:HAS_POST]->(this_posts:Post)   | this_posts { .id } ], ['^title']) } as this
Params:
{
  "this_id": "1"
} +1m
  @neo4j/graphql:execute Execute successful, received 1 records +3ms
```

**Comment by neo4j-team-graphql** [comment] 2022-01-12 06:36
Many thanks for raising this bug report @dmoree. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment] 2022-01-12 10:06
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @dmoree! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment] 2022-01-12 10:07
Thanks for raising this @dmoree, and for getting a fix in so quickly! This is actually a duplicate of the super old #160 which we just never got around to. Will leave both of them open but mark them both resolved by your PR. 🙂

**Comment by dmoree** [comment] 2022-01-12 16:49
Sorry about the oversight. Super old for sure that example is from `1.0.0-beta.2`. Thanks again.

**Closed** 2022-01-19 11:04 UTC
Labels: confirmed, bug report
