### ISSUE TITLE
Compatibility of @neo4j/graphql with neo4j-driver

### ISSUE THREAD

**Issue by GeoffThorpeFT** [neo4j/graphql#5130] opened 2024-05-15 11:07 UTC
We have recently upgraded our `@neo4j/graphql` library from `v3.17.1` to `v4.4.6`. Whilst doing so we noted the peer dependency on v5 of the `neo4j-driver` so we duly upgraded that from `v4.4.10` to `v5.20.0`.  Everything appeared to work
at first but then we noticed graphQL was not working as expected when using `null` in filters.

We have been testing the following typedefs and query using various combinations of the driver versions:

```
const typeDefs = `#graphql
  type Team {
	code: String
	name: String
	delivers: [System!]! @relationship(type: "DELIVERED_BY", direction: IN)
  }

  type System {
	code: String
	name: String
	deliveredBy: Team @relationship(type: "DELIVERED_BY", direction: OUT)
  }`;

{
  systems(where: { deliveredBy: null }) {
    code
    deliveredBy {
      code
    }
  }
}
```

Your version compatibility support page: https://neo4j.com/developer/kb/neo4j-supported-versions/ is very helpful but may have a gap; it is not precise about the compatibility of **both** drivers - neo4j and graphql. Do they both have to be the same version?

We have found (in a node18 or node20 environment) running a neo4j v4.4 database that:

- v4.4.6 of @neo4j/graphql and v4.4.11 of neo4j-driver are NOT compatible due to the peer v5 driver dependency introduced in v4 of graphql
- v5.3.6 of @neo4j/graphql works with v5.20.0 of neo4j-driver
- v4.4.6 of @neo4j/graphql appears to work with v5.20.0 of neo4j-driver but the `deliveredBy:null` filter above is ignored and all the system records are shown. A `{deliveredByAggregate: {count:0}}` filter is successful.
- Previously v3.17.1 of @neo4j/graphql did work with v4.4.10 of neo4j-driver.

Does the above now mean that an upgrade from v3 to v4 of the graphql driver now forces you to go to v5 of the neo4j-driver?
That in turn seems to force you to upgrade to v5 of graphql driver :help:

**Comment by neo4j-team-graphql** [comment] 2024-05-15 11:08
Many thanks for raising this bug report @GeoffThorpeFT. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment] 2024-05-15 13:54
Hey @GeoffThorpeFT, this sounds almost like it is not a driver problem, but we are failing to translate the `null` value into checking that a relationship does not exist. This actually rings a bell about a bug which existed at some point.

I notice you are not moving to version 5 of the GraphQL Library, is there any reason for that? We no longer release bug fixes for version 4 of the library.

**Comment by GeoffThorpeFT** [comment] 2024-05-15 14:07
Thanks for the swift response @darrellwarde . We are on the way to v5 of the graphql library but as we were only on v3 we were aiming to to it in stages. Unfortunately as you can see the v3->v4 upgrade didnt work as we expected. 
As you no longer release bug fixes to v4 are you telling us we have to go v5 ? 😄

**Comment by darrellwarde** [comment] 2024-05-15 15:32
Let's dig into it a little bit more, could you possibly provide the generated Cypher for one of these offending queries? Execute `node` prepended with `DEBUG=@neo4j/graphql:*` and when you execute the query, it will print the generated Cypher to the console. I want to see if this is indeed what I suspect.

**Comment by GeoffThorpeFT** [comment] 2024-05-16 07:13
Thanks @darrellwarde for the follow up. Here are some snippets from the DEBUG output when running graphql v4.4.6 against driver v5.20.0:

```
  @neo4j/graphql:graphql   params: {
  @neo4j/graphql:graphql     query: '{\n' +
  @neo4j/graphql:graphql       '  systems(where: {deliveredBy: null}) {\n' +
  @neo4j/graphql:graphql       '    code\n' +
  @neo4j/graphql:graphql       '    deliveredBy {\n' +
  @neo4j/graphql:graphql       '      code\n' +
  @neo4j/graphql:graphql       '    }\n' +
  @neo4j/graphql:graphql       '  }\n' +
  @neo4j/graphql:graphql       '}',
  @neo4j/graphql:graphql     extensions: {}
  @neo4j/graphql:graphql   },
```

```
  @neo4j/graphql:translate ReadOperation
  @neo4j/graphql:translate |──── NodeSelection
  @neo4j/graphql:translate |──── RelationshipFilter [deliveredBy] <NOT SOME>
  @neo4j/graphql:translate |──── AttributeField <code>
  @neo4j/graphql:translate |──── OperationField <deliveredBy>
  @neo4j/graphql:translate |     |──── ReadOperation
  @neo4j/graphql:translate |           |──── RelationshipSelection
  @neo4j/graphql:translate |           |──── AttributeField <code> +38s
  @neo4j/graphql:execution executing cypher +38s
  @neo4j/graphql:execution MATCH (this:System)
  @neo4j/graphql:execution CALL {
  @neo4j/graphql:execution     WITH this
  @neo4j/graphql:execution     MATCH (this)-[this0:DELIVERED_BY]->(this1:Team)
  @neo4j/graphql:execution     WITH this1 { .code } AS this1
  @neo4j/graphql:execution     RETURN head(collect(this1)) AS var2
  @neo4j/graphql:execution }
  @neo4j/graphql:execution RETURN this { .code, deliveredBy: var2 } AS this +0ms
  @neo4j/graphql:execution cypher params: {} +0ms
  @neo4j/graphql:execution Execute successful, received 3087 records +38s
```

**Comment by GeoffThorpeFT** [comment] 2024-05-16 07:21
When running graphql v5.3.6 with driver v5.20.0 the output is correct (in my very simple test example) and the DEBUG log is as follows:

```
  @neo4j/graphql:translate ReadOperation
  @neo4j/graphql:translate |──── NodeSelection
  @neo4j/graphql:translate |──── RelationshipFilter [deliveredBy] <NOT SOME>
  @neo4j/graphql:translate |──── AttributeField <code>
  @neo4j/graphql:translate |──── OperationField <deliveredBy>
  @neo4j/graphql:translate |     |──── ReadOperation
  @neo4j/graphql:translate |           |──── RelationshipSelection
  @neo4j/graphql:translate |           |──── AttributeField <code> +0ms
  @neo4j/graphql:execution executing cypher +64ms
  @neo4j/graphql:execution MATCH (this:System)
  @neo4j/graphql:execution WHERE NOT (EXISTS {
  @neo4j/graphql:execution     MATCH (this)-[:DELIVERED_BY]->(this0:Team)
  @neo4j/graphql:execution })
  @neo4j/graphql:execution CALL {
  @neo4j/graphql:execution     WITH this
  @neo4j/graphql:execution     MATCH (this)-[this1:DELIVERED_BY]->(this2:Team)
  @neo4j/graphql:execution     WITH this2 { .code } AS this2
  @neo4j/graphql:execution     RETURN head(collect(this2)) AS var3
  @neo4j/graphql:execution }
  @neo4j/graphql:execution RETURN this { .code, deliveredBy: var3 } AS this +0ms
  @neo4j/graphql:execution cypher params: {} +0ms
  @neo4j/graphql:execution Execute successful, received 260 records +0ms
```

I can see the difference/bug you said might be occurring. The newer graphql version is capable of translating the `null` request into an `WHERE NOT EXISTS` check 🤔 

Our real schema/typedefs are large with over 150 1-2-many relationships that have the potential to hit the `null` filter issue. We also have over 30 interfaces that need to be tweaked for the v5 graphql migration.

**Comment by MacondoExpress** [comment] 2024-05-16 08:29
I believe this was fixed by https://github.com/neo4j/graphql/pull/4762 and released on version 5.x!

**Comment by i-like-robots** [comment] 2024-05-20 14:58
Thanks for the update @MacondoExpress, we're pleased to hear this is a recognised issue which has been resolved in recent versions.

However, whilst upgrading to v5 is on our roadmap the upgrade to v5 has an impact on our customers due to the [changes made to accessing edge properties](https://neo4j.com/docs/graphql/current/migration/#_edge_properties). As our API has heavy usage from many customers this upgrade will take us some time to plan, communicate, and roll out.

Is there any possibility of this fix being backported to v4? If not, is there any way we could we help to make this happen?

**Comment by MacondoExpress** [comment] 2024-05-20 15:52
Hi @i-like-robots ,
We understand that this issue could result in a migration pain to users of the library, and for this reason, we're looking to back-port this bug fix on a non-LTS version of the library. We'll keep you posted.

**Comment by i-like-robots** [comment] 2024-05-20 20:30
Thank you for the update @MacondoExpress, we (and our users!) would really appreciate if you could make this happen 🤞

**Comment by GeoffThorpeFT** [comment] 2024-05-21 12:49
@darrellwarde @MacondoExpress  I have a related question about the v5 upgrade and its use of `properties` as the new container for `edges` properties ....

Your v5 graphql docs are clear https://neo4j.com/docs/graphql/current/migration/#_edge_properties that any reference to the output of `edges` that contains relationship properties must now enclose those properties in a `properties` object.
However, I dont see a similar requirement if edge properties are used in filters 🤔   That concerns me a lot as it suggests filters can understand the properties at a different nested level to the actual output.  Here is an example:

```
{
  systems(
    where: {
      lifecycleStage_IN: [Preproduction, Production]
      installsPackagesConnection_SOME: {
					AND: [
            {node: { code: "npm:@financial-times/n-express" }},
            {edge: { NOT: { versionRange_STARTS_WITH: "31." } }}.   <<<<<<<< why dont we need properties{} here?
					]
      }
    }
  ) {
    team: deliveredBy {
      code
    }
    code
    packages: installsPackagesConnection(
      where: {
            AND: [
              { node: { code: "npm:@financial-times/n-express" } }
              { edge: { NOT: { versionRange_STARTS_WITH: "31." } } }.        <<<<<<<< why dont we need properties{} here?
            ]
      }
    ) {
      edges {
        properties {.                 <<<<<<<<<<<<<<<<<< this is required in v5
          versionRange
        }
        node {
          code
        }
      }
    }
  }
}
```

**Comment by MacondoExpress** [comment] 2024-05-21 14:31
Hi @GeoffThorpeFT, 
The API evolved at a different pace, which resulted in an inconsistent API in some cases, to fix that we designed a consistent and uniform API, unfortunately, the migration steps required to reach that API were too much for a single major release, and we have chosen to achieve it in smaller incremental steps. I'm happy to hear your concern over that particular as it will be one of the inconsistencies that we're planning to remove next!
In case you're interested we have a Discord channel for this kind of questions:
https://discord.com/channels/787399249741479977/818578492723036210 
I feel it would reach a wider audience than this issue.

**Comment by MacondoExpress** [comment] 2024-05-30 10:47
Hi @GeoffThorpeFT , @i-like-robots ,
We have released version `4.4.7` which contains the fix for this issue.

**Closed as completed by MacondoExpress** 2024-05-30 10:47 UTC
Labels: bug

**Comment by i-like-robots** [comment] 2024-05-30 14:31
That's great news, thank you @MacondoExpress - I hope we will try out the release next week 😃

**Comment by i-like-robots** [comment] 2024-06-24 13:41
I just wanted to follow up on this to say that we were able to upgrade to v4.4.7 and this has successfully resolved the query issues our users were having. Many thanks 👏

**Comment by MacondoExpress** [comment] 2024-07-01 08:18
> I just wanted to follow up on this to say that we were able to upgrade to v4.4.7 and this has successfully resolved the query issues our users were having. Many thanks 👏

That's very nice to hear!
