### ISSUE TITLE
Support sorting on n:1 relations

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#4168] opened 2023-10-19 10:35 UTC
Consider a schema like this:

```graphql
interface Bar {
  val: String!
}

interface Foo {
  test: String!
  bar: Bar! @relationship(...)
}

```

Each Foo has one bar and it would therefore be nice to be able to use "bar.val" as a sort criteria. This is currently not possible. However it would be possible to support it without significantly enlarging the schema, because all Sort-Types are already present.

In other words, it would be nice if the generated FooSort type would have a "bar" field that refers to the "BarSort" type and then sorting would be possible accordingly.

**Comment by darrellwarde** [comment] 2023-10-19 12:08
Thanks, this is absolutely on the to-do list, currently pencilled in for early next year! But we're also happy to accept contributions for these kinds of features.

**Comment by darrellwarde** [comment] 2024-02-21 15:50
Duplicate of #145.

**Closed by darrellwarde** 2024-02-21 15:50 UTC
Labels: feature request
