### ISSUE TITLE
@authorization: unable to do update with nested create without explicitly connecting to the source node

### ISSUE THREAD

**Issue by v-makh** [neo4j/graphql#3939] opened 2023-09-12 21:31 UTC
### Type definitions

```GraphQL
type Group
  {
    id: ID! @id @unique
    name: String!
    invitees: [Invitee!]! @relationship(type: "INVITED_TO", direction: IN, aggregate: true)
  }

  type Invitee
    @authorization(validate: [{ operations: [CREATE], where: { node: { group: { inviteesAggregate: { count_LT: 5 }}}}}])
  {
    id: ID! @id @unique
    group: Group! @relationship(type: "INVITED_TO", direction: OUT)
    email: String!
  }

  extend schema @authentication
```

### Test data

```Shell
See below.
```

### Steps to reproduce

Create a group:
```graphql
mutation CreateGroups($input: [GroupCreateInput!]!) {
  createGroups(input: $input) {
    info {
      nodesCreated
    }
  }
}
```
variables: 
```json
{
  "input": [
    {
      "name": "test"
    }
  ]
}
```

Next, try to add invitee to the group:
```graphql
mutation UpdateGroups($create: GroupRelationInput, $where: GroupWhere) {
  updateGroups(create: $create, where: $where) {
    groups {
      invitees {
        id
        email
        group { id }
      }
    }
  }
}
```
variables:
```json
{
   "where": {
    "id": "group_id"
  },
  "create": {
    "invitees": [
      {
        "node": {
          "email": "test@test.com",
        }
      }
    ]
  }
}
```

### What happened

I get the following error:
```json
"errors": [
    {
      "message": "Forbidden",
```

If I remove the `@authorization` directive on `Invitee`, the mutation goes through and I can see the new invitee and its group field populated correctly. It also works if I change the variables and connect the source group explicitly in `create.invitees.node`:
```json
{
   "where": {
    "id": "group_id"
  },
  "create": {
    "invitees": [
      {
        "node": {
          "email": "test@test.com",
          "group": {
            "connect": {
              "where": {
                "node": {
                  "id": "group_id"
                }
              }
            }
          }
        }
      }
    ]
  }
}
```

### Expected behaviour

I would've expected the mutation to work with the given variables and authorization rules without having to explicitly connect invitee back to the source `group` in the `create` section of the variables, since this is implied.

### Version

4.1.1

### Database version

Aura Professional 5

**Comment by neo4j-team-graphql** [comment] 2023-09-12 21:31
Many thanks for raising this bug report @v-makh. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment] 2023-09-12 21:31
Many thanks for raising this bug report @v-makh. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment] 2023-09-13 08:02
Thanks for the report. This is a duplicate of #3901, we're aware of the issue and are investigating!

**Closed by darrellwarde** 2023-09-13 08:02 UTC
Labels: bug report
