### ISSUE TITLE
Multiple properties update on single node yields multiple events

### ISSUE THREAD

**Issue by angrykoala** [neo4j/graphql#1573] opened 2022-06-14 11:40 UTC
**Describe the bug**
If an update operations modifies multiple properties. A new event is triggered per property, instead of a single update event.

**Example**

Given the typedefs:

```gql
type Movie{
    id: ID!
    name: String
    tagline: String
}
```

The following mutation:
```gql
mutation {
    updateMovie(where: { id: "1" }, update: { name: "The Matrix", tagline: "Don't worry about cookies" }) {
        movies {
            id
        }
    }
}
```

Will yield 2 update events in any subscription (one for name, and another for tagline) instead of a single event with all the changes.

The generated cypher is (roughly):

```cypher
WITH [] AS meta
MATCH (this:Movie)
WHERE this.id = 1

WITH this { .* } AS oldProps, this, meta
SET this.name = "The Matrix"
WITH this, meta + { event: "update", id: id(this), properties: { old: oldProps, new: this { .* } }, timestamp: timestamp(), typename: "Movie" } AS meta
WITH this { .* } AS oldProps, this, meta
SET this.tagline = "Don't worry about cookies"
WITH this, meta + { event: "update", id: id(this), properties: { old: oldProps, new: this { .* } }, timestamp: timestamp(), typename: "Movie" } AS meta

WITH this, meta
UNWIND meta AS m
RETURN collect(DISTINCT this { .id }) AS data, collect(DISTINCT m) as meta
```

The expected cypher should be:

```cypher
WITH [] AS meta
MATCH (this:Movie)
WHERE this.id = 1

WITH this { .* } AS oldProps, this, meta
SET this.name = "The Matrix"
SET this.tagline = "Don't worry about cookies"
WITH this, meta + { event: "update", id: id(this), properties: { old: oldProps, new: this { .* } }, timestamp: timestamp(), typename: "Movie" } AS meta

WITH this, meta
UNWIND meta AS m
RETURN collect(DISTINCT this { .id }) AS data, collect(DISTINCT m) as meta
```

**Comment by neo4j-team-graphql** [comment] 2022-06-14 11:40
Many thanks for raising this bug report @angrykoala. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment] 2022-06-21 12:48
@angrykoala, can you make sure that PRs are linked to issues in future? This will ensure that the issue is closed when the PR is merged and avoid hanging issues.

**Closed by darrellwarde** 2022-06-21 12:48 UTC
Labels: confirmed, bug report, high priority
