### ISSUE TITLE
keep the consistency of default sort Both query and nested Query 

### ISSUE THREAD

**Issue by AnsonHwang86** [neo4j/graphql#1261] opened 2022-04-14 02:25 UTC
Hello, when I add a new node with create mutation.
The new added node is return in the front of result instead of last one.
This behavior seems weird.
Can query result set the default sort to created time of node both in single query and nested Query?

I would like to think it of bug instead of feature request.

Let put an example.

Schema:
```
type Human {
	  id:ID @id
	  name: String @unique
	  blog: [Blog!]! @relationship(type:"HAS_BLOG", direction: OUT)
	}

	type Blog{
	  id:ID @id
	  name: String @unique
	  comment: [Comment!]! @relationship(type:"WITH_COMMENT", direction: OUT)
	}

	type Comment {
	  id:ID @id
	  name: String @unique
	  author: Author @relationship(type:"AUTHOR_IS", direction: OUT)
	}
```
Mutation
```
mutation createHm{
	createHumans(input:[
		{
			name:"humanname1"
			blog:{
				create:{
					node:{
						name:"blogname1"
						comment:{
							create:{
								node:{
									name:"commentname1"
								}
							}
						}
					}
				}
			}
		}
	]){
		humans{
			id
			name
			blog{
				id
				name
				comment{
					id
					name
				}
			}
		}
	}
}
```
update mutation
```
mutation humanss{
	updateHumans(
		where:{
			name:"humanname1"
		}
		update:{
			blog:{
				create:{
					node:{
						name:"blogname2"
					}
				}
			}
		}
	){
		humans{
			id
			name
			blog{
				id
				name
			}
		}
	}
}
```
the result as following
```
{
	"data": {
		"updateHumans": {
			"humans": [
				{
					"id": "de1b75a0-ff33-419d-a3a3-39912b7f14a3",
					"name": "humanname1",
					"blog": [
						{
							"id": "97efce0a-ce67-4bed-b482-e7599260f1da",
							"name": "blogname2"
						},
						{
							"id": "5da2e8e8-9834-4caa-80a2-2836e9f300b1",
							"name": "blogname1"
						}
					]
				}
			]
		}
	}
}
```
what I except is (the sort of blog is by createtime)

```
{
	"data": {
		"updateHumans": {
			"humans": [
				{
					"id": "de1b75a0-ff33-419d-a3a3-39912b7f14a3",
					"name": "humanname1",
					"blog": [
						{
							"id": "5da2e8e8-9834-4caa-80a2-2836e9f300b1",
							"name": "blogname1"
						},
						{
							"id": "97efce0a-ce67-4bed-b482-e7599260f1da",
							"name": "blogname2"
						}
					]
				}
			]
		}
	}
}
```
If I run single query
```
query blog{
	blogs{
		id
		name
	}
}
```
The result return is sort by Node's created time as following as expected

```
{
	"data": {
		"blogs": [
			{
				"id": "5da2e8e8-9834-4caa-80a2-2836e9f300b1",
				"name": "blogname1"
			},
			{
				"id": "97efce0a-ce67-4bed-b482-e7599260f1da",
				"name": "blogname2"
			}
		]
	}
}
```

Yes, I know the way to pass this confuse by add createdAt field to type schema and query by options's sort.
But I think it's import to make it consistency Both query and nested Query

**Comment by neo4j-team-graphql** [comment] 2022-04-14 02:25
Many thanks for raising this bug report @AnsonHwang86. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment] 2022-04-29 14:54
@angrykoala I think we should revisit that decision, as I believe what is really being requested here is some way to specify the default sorting when being returned a particular type, for example:

```gql
type Human {
    id:ID @id
    name: String @unique @defaultSort(direction: ASC)
    blog: [Blog!]! @relationship(type:"HAS_BLOG", direction: OUT)
}
```

If this is indeed the case, then we should treat as feature request.

**Comment by angrykoala** [comment] 2022-04-29 15:13
@darrellwarde I may be wrong, but according to the examples provided and the name of this issue, it seems clear that this does not refer to a new "sort" directive, but to the consistency of sort between mutations vs query

Maybe this could be solved with a directive as a new feature, but until we reach that conclusion, it doesn't feel like a feature request.

**Comment by AnsonHwang86** [comment] 2022-05-06 00:10
@darrellwarde @angrykoala default sort is another topic. My question in this issues is the default sort by @neo4j/graphql for all data. Yes, add defaultSort directive will solved my question. But I think it's better to add the default sort in @queryOptions
By now, the defualt `limit` can be set in @queryOptions directive.
I will open another issue to talk this topic.

**Comment by darrellwarde** [comment] 2024-02-21 16:18
Closing as a duplicate of #499.

**Closed by darrellwarde** 2024-02-21 16:18 UTC
Labels: enhancement
