### ISSUE TITLE
Fail to enforce(keep) relationship cardinality constraint on connect

### ISSUE THREAD

**Issue by AnsonHwang86** [neo4j/graphql#1163] opened 2022-03-22 02:42 UTC
**Describe the bug**

**Type definitions**

```gql
type Foo {
  uuid:ID @id
  name: String @unique
  sth: String
  bar: [Bar!]! @relationship(type:"HAS", direction:OUT)
}

type Bar {
  uuid:ID @id
  name: String @unique
  sth: String
  foo: Foo @relationship(type:"HAS", direction:IN)
}
```

**To Reproduce**

```gql
mutation createBar2{
	createBars(input:[
		{name:"bar"}
	]){
		bars{
			uuid
		}
	}
}

mutation createFoo1{
	createFoos(input:[
		{name:"foo1"}
	]){foos{uuid}}
}


mutation createFoo2{
	createFoos(input:[
		{name:"foo2"}
	]){foos{uuid}}
}

#connect foo1 to bar
mutation connectBarAndFoo1{
	updateFoos(where:{
		name:"foo1"
	}
	connect:{bar:{where:{node:{name:"bar"}}}}
	){
		foos{
			uuid
		}
	}
}

#connect foo2 to bar
# this mutation should be fails, each node of Bar type should have a only node of Foo type as description in schema. But when run it, it still successful be run and connect foo2 to bar.
mutation connectBarAndFoo2{
	updateFoos(where:{
		name:"foo2"
	}
	connect:{bar:{where:{node:{name:"bar"}}}}
	){
		foos{
			uuid
		}
	}
}

# run the below mutation, it will throw an error - "Bar.foo must be less than or equal to one"
mutation updateBar{
	updateBars(
		where:{name:"bar"}
	  update:{sth:"something"}
	){
		bars{uuid}
	}
}
```

**Expected behavior**

It should keep the contrainst accordingly when operate connect.

**Screenshots**

**System (please complete the following information):**

* OS:Windows 10
* Version: [e.g. @neo4j/graphql@3.0.3]

**Additional context**

**Comment by neo4j-team-graphql** [comment] 2022-03-22 02:42
Many thanks for raising this bug report @AnsonHwang86. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment] 2022-03-22 10:58
Hey @AnsonHwang86, this is a valid bug report, but not one which is going to get looked at for now. A similar scenario is documented at https://neo4j.com/docs/graphql-manual/current/troubleshooting/faqs/#_relationship_nullability_isnt_being_enforced_in_my_graph and basically, this is because we can only easily check these constraints from the source node of a Mutation. To also perform these checks from target nodes is a completely different beast and adds a lot of complexity.

**Comment by neo4j-team-graphql** [comment] 2022-03-22 10:59
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AnsonHwang86! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment] 2024-02-22 16:50
Our direction is moving towards only supporting relationship cardinalities supported by the database, so we're going to close this as a won't do.

**Closed by darrellwarde** 2024-02-22 16:50 UTC
Labels: confirmed, bug report, reopened
