### ISSUE TITLE
onCreate for connectOrCreate should allow nested mutations

### ISSUE THREAD

**Issue by danielfein** [neo4j/graphql#1080] opened 2022-03-02 04:45 UTC
**Is your feature request related to a problem? Please describe.**
When using `connectOrCreate` and the node does not exist, users should be able to connect the new node as they would with a standard `create` mutation.

**Describe the solution you'd like**
You'll see here an example of what this might look like, as currently it goes against expected behavior: https://github.com/neo4j/graphql/issues/1068

**Comment by darrellwarde** [comment] 2022-09-28 18:48
Closing as a duplicate of #1552, we definitely want to get this done!

**Closed by darrellwarde** 2022-09-28 18:48 UTC
Labels: feature request
