### ISSUE TITLE
Cannot query 2 resolvers in same query

### ISSUE THREAD

**Issue by fnfbraga** [neo4j/graphql#672] opened 2021-12-27 11:51 UTC
**Describe the bug**
For recent versions trying to query 2 resolvers in the same query throws error: "Cannot convert undefined or null to object". Cypher is incorrectly generated:

`  @neo4j/graphql:graphql Incoming GraphQL:
Query:
query Test {
  patients {
    id
    __typename
  }
  claims {
    id
    __typename
  }
}
Variables:
{} +0ms
  @neo4j/graphql:auth JWT not configured +1ms
  @neo4j/graphql:execute About to execute Cypher:
Cypher:
MATCH (this:Claim)
RETURN this { .id } as this
`
As you can see above only the cypher query for Claims is generated, not for Patients.

**Comment by neo4j-team-graphql** [comment] 2021-12-27 11:55
Many thanks for raising this bug report @fnfbraga. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

Thanks again! :pray:

**Comment by darrellwarde** [comment] 2022-01-11 12:18
@fnfbraga, can you please confirm for me whether or not this is still the case? I believe this might be fixed by #639.

If you're still having issues, can you please provide a more comprehensive description including type definitions and query to execute so that we can easily reproduce? Thanks!

**Comment by darrellwarde** [comment] 2022-01-18 13:05
I'm going to close this due to inactivity and the belief that this is fixed. Feel free to reopen and update if this isn't accurate!

**Closed by darrellwarde** 2022-01-18 13:05 UTC
Labels: bug report

**Comment by fnfbraga** [comment] 2022-01-19 11:31
Thank you, just did a quick test and seems to work fine.
