### ISSUE TITLE
Error: Unknown directive "@auth"

### ISSUE THREAD

**Issue by harryjin** [neo4j/graphql#3030] opened 2023-03-13 17:53 UTC
**Describe the bug**
During migrating from neo4j-graphql-js to @neo4j/graphql, it don't recognize @auth directive.

**Type definitions**
Type definitions

**To Reproduce**
1. Make Schema with @auth directive

```
type URL @auth(rules: [{ isAuthenticated: true }]) {
  _id: ID!
  address: String!
  status_code: Int
  canonical: String
  title_1: String
  titleLen: Int
  h1_1: String
  h1_1Len: Int
  fullText: String
  fullHTMLText: String
  links: [URL!]! @relationship(type: "LINKS_TO", direction: OUT)
  outlinks: Int
  inlinks: Int
}

```
2. Build the project and Run.
3. When get schema, this error occur.
`  const schema = await neoSchema.getSchema()`

**Screenshots**
![image](https://user-images.githubusercontent.com/1405854/224786751-c1b57f6b-ab5b-40c6-a78f-e6b797cfe1c6.png)

**System (please complete the following information):**

* OS: [e.g. macOS, Windows]
* Version: [e.g. @neo4j/graphql@3.6]
* Node.js version: [e.g. 16.10.0]

**Additional context**

**Comment by neo4j-team-graphql** [comment] 2023-03-13 17:53
Many thanks for raising this bug report @harryjin. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment] 2023-03-13 17:53
Many thanks for raising this bug report @harryjin. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by MacondoExpress** [comment] 2023-03-13 20:01
I tried to reproduce your issue with the latest version of the library 3.17.1, with the reproduction step that you have provided without any success.
Could you share more details on how to reproduce it?
I can share the reproduction step I've used:
```typescript
async function run() {
    const driver = neo4j.driver("bolt://localhost:7687", neo4j.auth.basic("user", "password"));
    const typeDefs = gql`
        type URL @auth(rules: [{ isAuthenticated: true }]) {
            _id: ID!
            address: String!
            status_code: Int
            canonical: String
            title_1: String
            titleLen: Int
            h1_1: String
            h1_1Len: Int
            fullText: String
            fullHTMLText: String
            links: [URL!]! @relationship(type: "LINKS_TO", direction: OUT)
            outlinks: Int
            inlinks: Int
        }
    `;
    const neoSchema = new Neo4jGraphQL({
        typeDefs,
        driver,
        plugins: {
            auth: new Neo4jGraphQLAuthJWTPlugin({
                secret: "secret",
                noVerify: false,
            }),
        },
    });

    const schema = await neoSchema.getSchema();
}
run()
```

**Comment by harryjin** [comment] 2023-03-13 20:09
Thanks for your help. Please try follow schema.
`type User {
  userId: ID!
  name: String
  reviews: [Review!]! @relationship(type: "WROTE", direction: OUT)
  avgStars: Float
    @cypher(
      statement: "MATCH (this)-[:WROTE]->(r:Review) RETURN toFloat(avg(r.stars))"
    )
  numReviews: Int
    @cypher(statement: "MATCH (this)-[:WROTE]->(r:Review) RETURN COUNT(r)")
  recommendations(first: Int = 3): [Business]
    @cypher(
      statement: "MATCH (this)-[:WROTE]->(r:Review)-[:REVIEWS]->(:Business)<-[:REVIEWS]-(:Review)<-[:WROTE]-(:User)-[:WROTE]->(:Review)-[:REVIEWS]->(rec:Business) WHERE NOT EXISTS( (this)-[:WROTE]->(:Review)-[:REVIEWS]->(rec) ) WITH rec, COUNT(*) AS num ORDER BY num DESC LIMIT $first RETURN rec"
    )
}

type URL @auth(rules: [{ isAuthenticated: true }]) {
  _id: ID!
  address: String!
  status_code: Int
  canonical: String
  title_1: String
  titleLen: Int
  h1_1: String
  h1_1Len: Int
  fullText: String
  fullHTMLText: String
  links: [URL!]! @relationship(type: "LINKS_TO", direction: OUT)
  outlinks: Int
  inlinks: Int
}

type Business @auth(rules: [{ isAuthenticated: true }]) {
  businessId: ID!
  name: String!
  address: String
  city: String
  state: String
  location: Point
  avgStars: Float
    @cypher(
      statement: "MATCH (this)<-[:REVIEWS]-(r:Review) RETURN coalesce(avg(r.stars),0.0)"
    )
  reviews: [Review!]! @relationship(type: "REVIEWS", direction: IN)
  categories: [Category!]! @relationship(type: "IN_CATEGORY", direction: OUT)
}

type Review {
  reviewId: ID!
  stars: Float
  text: String
  date: Date
  business: Business @relationship(type: "REVIEWS", direction: OUT)
  user: User @relationship(type: "WROTE", direction: IN)
}

type Category {
  name: ID!
  businesses: [Business!]! @relationship(type: "IN_CATEGORY", direction: IN)
}

type RatingCount @exclude {
  stars: Float!
  count: Int!
}

type Mutation {
  mergeBusinessCategory(categories: [String!]!, businessId: ID!): Business
    @cypher(
      statement: "MATCH (b:Business {businessId: $businessId}) UNWIND $categories AS cat MERGE (c:Category {name: cat}) MERGE (b)-[:IN_CATEGORY]->(c) RETURN b"
    )

  initiateNewCrawl(crawlOptions: InitiateNewCrawlOptions!): InitiateNewCrawlResult
    @auth(rules: [{ isAuthenticated: true }])

  startCrawl(crawlOptions: StartCrawlOptions!): StartCrawlResult
    @auth(rules: [{ isAuthenticated: true }])
}

input InitiateNewCrawlOptions {
  startingUrl: String!
  crawlId: String
}

type InitiateNewCrawlResult {
  crawlId: String!
  seoConfigUploadUrl: String!
}

input StartCrawlOptions {
  crawlId: String!
  startingUrl: String!
  skipCrawl: Boolean
}
type StartCrawlResult {
  crawlId: String!
}


type UserProfile {
  id: String!
  email: String!
  tenant: String!
}

type URLCommunitySummary {
  lpa: Int!
  count: Int!
  addresses: [String!]!
}

type LinkedURL {
  address: String!
  anchor: String
  lpa: Int
  title: String
  linkPosition: String
}

type Query {
  ratingsCount: [RatingCount]
    @cypher(
      statement: "MATCH (r:Review) WITH r.stars AS stars, COUNT(*) AS count ORDER BY stars RETURN {stars: stars, count: count}"
    )

  myProfile: UserProfile
    @auth(rules: [{ isAuthenticated: true }])

  urlCount: Int!
    @auth(rules: [{ isAuthenticated: true }])
    @cypher(statement: "MATCH (u:URL) RETURN COUNT(u)")

  urlReport(first: Int = 10, offset: Int = 0): [URL]
    @auth(rules: [{ isAuthenticated: true }])
    @cypher(
      statement: """
        MATCH
          (s:URL)-[inl:LINKS_TO]->(n:URL)-[ol:LINKS_TO]->(d:URL)
        WHERE
          NOT n.address=d.address
          AND NOT s.address=n.address
          AND NOT s.address=d.address
          AND n.status_code=200
        RETURN n
        ORDER BY n.inlinks
        SKIP toInteger($offset)
        LIMIT toInteger($first)
        """
    )

  """
  Get the top X URL communities using LPA to group each URL into a community
  """
  topURLCommunities(first: Int = 5, offset: Int = 0): [URLCommunitySummary]
    @auth(rules: [{ isAuthenticated: true }])
    @cypher(
      statement: """
        MATCH (n:URL)
        WHERE n.lpa IS NOT NULL
        WITH n, n.address as address, n.lpa as `lpa`
        RETURN {
          addresses: collect(address),
          count: count(address),
          lpa: lpa
        } as row
        ORDER BY row.count DESC
        SKIP toInteger($offset)
        LIMIT toInteger($first)
        """
    )

  """
  Get the outbound link profile of a specific URL
  """
  outboundLinks(address: String!, limit: Int = 20 ): [LinkedURL]
    @auth(rules: [{ isAuthenticated: true }])
    @cypher(
      statement: """
        MATCH(s:URL)-[lt:LINKS_TO]->(p:URL)
        WHERE
            s.address = $address
            AND s.address <> p.address
        RETURN {
          address: p.address,
          lpa: p.lpa,
          anchor: lt.anchor,
          title: p.title_1,
          linkPosition: lt.link_position
        }
        LIMIT toInteger($limit)
        """
    )

  """
  Get the inbound link profile of a specific URL
  """
  inboundLinks(address: String!, limit: Int = 20 ): [LinkedURL]
    @auth(rules: [{ isAuthenticated: true }])
    @cypher(
      statement: """
        MATCH(s:URL)-[lt:LINKS_TO]->(p:URL)
        WHERE
            p.address = $address
            AND s.address <> p.address
        RETURN {
          address: s.address,
          lpa: s.lpa,
          anchor: lt.anchor,
          title: s.title_1,
          linkPosition: lt.link_position
        }
        LIMIT toInteger($limit)
        """
    )
}
`

**Comment by harryjin** [comment] 2023-03-13 20:12
> I tried to reproduce your issue with the latest version of the library 3.17.1, with the reproduction step that you have provided without any success. Could you share more details on how to reproduce it? I can share the reproduction step I've used:
> 
> ```ts
> async function run() {
>     const driver = neo4j.driver("bolt://localhost:7687", neo4j.auth.basic("user", "password"));
>     const typeDefs = gql`
>         type URL @auth(rules: [{ isAuthenticated: true }]) {
>             _id: ID!
>             address: String!
>             status_code: Int
>             canonical: String
>             title_1: String
>             titleLen: Int
>             h1_1: String
>             h1_1Len: Int
>             fullText: String
>             fullHTMLText: String
>             links: [URL!]! @relationship(type: "LINKS_TO", direction: OUT)
>             outlinks: Int
>             inlinks: Int
>         }
>     `;
>     const neoSchema = new Neo4jGraphQL({
>         typeDefs,
>         driver,
>         plugins: {
>             auth: new Neo4jGraphQLAuthJWTPlugin({
>                 secret: "secret",
>                 noVerify: false,
>             }),
>         },
>     });
> 
>     const schema = await neoSchema.getSchema();
> }
> run()
> ```

Thanks for your help. Please use follow schema.
https://drive.google.com/file/d/1uxj6l1cXxCZhEWzIbWx_Ty2rHZQ28CjX/view?usp=share_link

**Comment by darrellwarde** [comment] 2023-03-14 08:18
I haven't even reproduced, but given there are 3 errors, I'm 99% sure the problem fields are:

- `Mutation. initiateNewCrawl`
- `Mutation. startCrawl`
- `Query. myProfile`

You cannot use our `@auth` directive on a field resolved by a custom resolver. The `@auth` directive is assessed in Cypher, and with a custom resolver there is no Cypher.

**Comment by darrellwarde** [comment] 2023-03-15 11:46
Closing this one due to inactivity, and this is not a known problem. I suggest using something like GraphQL Shield if you want authentication on fields resolved by custom resolvers.

**Closed by darrellwarde** 2023-03-15 11:46 UTC
Labels: bug report
