### ISSUE TITLE
Type error for nodesDeleted field in auto-generated delete mutations

### ISSUE THREAD

**Issue by ankit-rawani** [neo4j/graphql#3213] opened 2023-04-18 09:55 UTC
**Describe the bug**
I'm facing one issue in any delete mutation generated by neo4j/graphql library. Check the screenshots below. When I try to query nodesDeleted, I get an error which says that "Int cannot represent non-integer value: 1".
I'm not getting any error if I don't query the nodesDeleted. 

This same error occurs when using the neo4j/graphql-ogm library.

**Type definitions**
```
type Allocation {
      id: ID @id
      tenantId: String!
      quantity: Int!
      verified: Boolean!
      lot: Lot @relationship(type: "PLACED_AT", direction: IN)
      inward: Inward @relationship(type: "PLACED_AT", direction: IN)
      warehouseSlot: WarehouseSlot! @relationship(type: "IS_AT", direction: OUT)
      sourceDepartment: Department @relationship(type: "SOURCED_FROM_DEPARTMENT", direction: OUT)
      sourceWarehouseSlot: WarehouseSlot @relationship(type: "SOURCED_FROM_WAREHOUSE_SLOT", direction: OUT)
  }

  extend type Allocation @auth(rules: [
      {
          allow: {
              tenantId: "$jwt.tenantId"
          }
      }
  ])
```

**To Reproduce**

1. Create a type definition.
2. Run the server.
3. Create a node and try deleting the created node using the auto-generated mutations. 
4. If we include the nodesDeleted field in the result, we'll get error regarding invalid type of the result. If we don't include this field, we won't get any error.

**Expected behavior**
It should just return the number of nodes deleted without any errors.

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/58520092/232739084-61d9c98e-724e-4df4-b661-76523b2d497f.png)
![image](https://user-images.githubusercontent.com/58520092/232739306-4519aff4-7b64-470b-8eff-0285db82cb9f.png)

**System (please complete the following information):**

* OS: Linux Mint 19.3 Tricia x86_64
* Version: @neo4j/graphql@3.18.1
* Node.js version: 16.15.0

**Additional Information**
These are the debug logs for this mutation -
```
  @neo4j/graphql:graphql Incoming GraphQL:
Query:
mutation DeleteAllocations($where: AllocationWhere) {
  deleteAllocations(where: $where) {
    bookmark
  }
}
Variables:
{
  "where": {
    "id_IN": [
      "e50cb47c-6989-4176-b930-a85286dada66"
    ]
  }
} +1m
  @neo4j/graphql:execute About to execute Cypher:
Cypher:
MATCH (this:`Allocation`)
WHERE this.id IN $param0
WITH this
CALL apoc.util.validate(NOT ((this.tenantId IS NOT NULL AND this.tenantId = $thisauth_param0)), "@neo4j/graphql/FORBIDDEN", [0])
DETACH DELETE this
Params:
{
  "param0": [
    "e50cb47c-6989-4176-b930-a85286dada66"
  ],
  "thisauth_param0": "9e342ced-b8c2-47ae-9bf7-0bedf5a85b9d"
} +1m
  @neo4j/graphql:execute Execute successful, received 0 records
```
```
  @neo4j/graphql:graphql Incoming GraphQL:
Query:
mutation DeleteUsers($where: UserWhere) {
  deleteUsers(where: $where) {
    nodesDeleted
  }
}
Variables:
{
  "where": {
    "id": "2398c7bd-a007-43aa-be69-4e20cffe6ee0"
  }
} +54s
  @neo4j/graphql:execute About to execute Cypher:
Cypher:
MATCH (this:`User`)
WHERE this.id = $param0
DETACH DELETE this
Params:
{
  "param0": "2398c7bd-a007-43aa-be69-4e20cffe6ee0"
} +54s
  @neo4j/graphql:execute Execute successful, received 0 records
```

**Comment by neo4j-team-graphql** [comment] 2023-04-18 09:55
Many thanks for raising this bug report @ankit-rawani. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment] 2023-04-20 05:31
Hi @ankit-rawani! Thanks for raising this bug.
I was trying to reproduce this bug yet wasn't successful.

Used the following type defs: 
```graphql
type Allocation {
        id: ID @id
        tenantId: String!
        quantity: Int!
        verified: Boolean!
}

extend type Allocation @auth(rules: [{ allow: { tenantId: "$jwt.tenantId" } }])
```

Then I created `Allocation`s like so:
```graphql
mutation CreateAllocations($input: [AllocationCreateInput!]!) {
  createAllocations(input: $input) {
    allocations {
      tenantId
      id
      quantity
    }
  }
}

-------
{
  "input": [
    {
      "quantity": 234,
      "tenantId": "theId",
      "verified": true
    }
  ]
}
```

Follow by the delete mutation:
```graphql
mutation Mutation($where: AllocationWhere) {
  deleteAllocations(where: $where) {
    bookmark
    nodesDeleted
    relationshipsDeleted
  }
}

--------
{
  "where": {
    "id_IN": ["5301873b-faad-48e0-81ad-3223d53ebdc7"]
  }
}
```

Debug log:
```
Query:
mutation Mutation($where: AllocationWhere) {
  deleteAllocations(where: $where) {
    bookmark
    nodesDeleted
    relationshipsDeleted
  }
}
Variables:
{
  "where": {
    "id_IN": [
      "5301873b-faad-48e0-81ad-3223d53ebdc7"
    ]
  }
} +40s
  @neo4j/graphql:execute About to execute Cypher:
Cypher:
MATCH (this:`Allocation`)
WHERE this.id IN $param0
WITH this
CALL apoc.util.validate(NOT ((this.tenantId IS NOT NULL AND this.tenantId = $thisauth_param0)), "@neo4j/graphql/FORBIDDEN", [0])
DETACH DELETE this
Params:
{
  "param0": [
    "5301873b-faad-48e0-81ad-3223d53ebdc7",
    "tets"
  ],
  "thisauth_param0": "theId"
}
```

**Comment by ankit-rawani** [comment] 2023-04-20 10:21
If possible, can you please share the outputs you're getting after running these mutations.

**Comment by tbwiss** [comment] 2023-04-20 11:44
Sure @ankit-rawani , this create mutation here (same as above):
```
mutation CreateAllocations($input: [AllocationCreateInput!]!) {
  createAllocations(input: $input) {
    allocations {
      tenantId
      id
      quantity
    }
  }
}

-------
{
  "input": [
    {
      "quantity": 234,
      "tenantId": "theId",
      "verified": true
    }
  ]
}
```

has the following response:
```
{
  "data": {
    "createAllocations": {
      "allocations": [
        {
          "tenantId": "theId",
          "id": "2da65c0e-fb30-404b-a500-356303977d66",
          "quantity": 234
        }
      ]
    }
  }
}
```

**Comment by tbwiss** [comment] 2023-05-02 08:51
Hi @ankit-rawani! Did this information help you to have a reproducible scenario? Thanks

**Comment by ankit-rawani** [comment] 2023-05-02 09:32
Hii @tbwiss 
Actually I'm not able to reproduce this error in a new project. It's just occuring in one specific project that I was working in. So I'm trying to figure it out. I'll let you know if I find anything.

**Comment by tbwiss** [comment] 2023-05-08 08:52
@ankit-rawani, I'll close this bug report since we're both not able to reproduce it.
If you find the issue in this one specific project that can be reproduced, feel free to open a new bug report.
Thank you!

**Closed by tbwiss** 2023-05-08 08:52 UTC
Labels: bug report, needs more information

**Comment by ankit-rawani** [comment] 2023-05-08 11:18
Sure
