### ISSUE TITLE
Case insensitive field comparisons

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#4117] opened 2023-10-13 09:57 UTC
It would be nice to support case-insensitive field comparisons especially in addition to CONTAINS.
This could translate to two TOLOWER() calls for now. This might be another operator CONTAINS_INSENSITIVE or it might be an option to change the case sensitivity per query.

I know that the same can be achieved by using a regular expression, but it's difficult for the client and does not using indexes.

Obviously the TOLOWER() does also not use indexes, but this seems like an issue that could still be addressed in neo4j and at least the client could send reasonable queries.

**Comment by darrellwarde** [comment] 2024-11-26 16:00
Closing as a duplicate of #4827!

**Closed by darrellwarde** 2024-11-26 16:00 UTC
Labels: enhancement
