### ISSUE TITLE
Strange schema validation error

### ISSUE THREAD

**Issue by acmeguy** [neo4j/graphql#384] opened 2021-08-03 12:20 UTC
**Describe the bug**
A valid GraphQL produces a validation error under certain circumstances.

**Type definitions**
If applicable, add your type definitions to help us reproduce the bug.

**To Reproduce**
I was trying things out and create the following/clumsy GraphQL that produces an error:

type DefinedTerm {
    id: ID @cypher(statement: """RETURN id(this) """)
    gid: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.gid """)
    gid_url: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.gid_url """)
    identifier: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.identifier """)
    sub_type: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.sub_type """)
    _labels: [String] @cypher(statement: "MATCH ()<-[this]-(source) return labels(source)")
}
** the input for this is a relationsship (this==rel/edge)

The error:
  UnhandledPromiseRejectionWarning: Error: Input Object type DefinedTermCreateInput must define one or more fields.
  Input Object type DefinedTermUpdateInput must define one or more fields.

Strangely the error goes away if I add a normal, non @cypher, field to the structure (something: String):

type DefinedTerm {
    id: ID @cypher(statement: """RETURN id(this) """)
    gid: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.gid """)
    gid_url: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.gid_url """)
    identifier: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.identifier """)
    sub_type: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.sub_type """)
    _labels: [String] @cypher(statement: "MATCH ()<-[this]-(source) return labels(source)")
    something: String
}

**Expected behavior**
Schema To be validates

**System (please complete the following information):**

-   OS: Windows
-   @neo4j/graphql@2.0.0 rc.1
-   Node.js version: 14.16.0

**Comment by darrellwarde** [comment] 2021-08-03 12:56
See https://github.com/neo4j/graphql/issues/269#issuecomment-863909103 and the comment following it for background on this one. Very difficult for us to do anything about it right now.

Also, it looks like you're trying to run custom Cypher from the context of a relationship - this isn't supported right now, it only works on node types. We were actually discussing custom Cypher and relationships this morning and came to the conclusion that it's most likely not actually necessary, you can just have custom Cypher on either of the nodes terminating the relationship instead.

**Comment by acmeguy** [comment] 2021-08-03 14:08
the relationship works in this @cypher statement :)
i was just playing with things when I came across this behaviour :)

**Comment by danstarns** [comment] 2021-08-03 14:42
Related https://github.com/neo4j/graphql/issues/269

**Comment by darrellwarde** [comment] 2021-08-03 14:55
Honestly I'm very confused by your type definitions. The `this` variable in Cypher for an object type is a node, yet you are using it in the context of a relationship, and I don't see how this would ever work.

**Comment by acmeguy** [comment] 2021-08-03 15:22
Well, the @cypher statement that invokes this type (DefinedTerm) return a relations and this works.
That is besides the point of the validation error, right?

**Comment by darrellwarde** [comment] 2021-08-03 15:57
I guess so! However, I would encourage you to turn on debug output (https://neo4j.com/docs/graphql-manual/current/troubleshooting/#_debug_logging) and validate that `this` is what you expect it to be in the compiled Cypher.

Another fix for this validation error would be to disable the relevant mutations:

```graphql
type DefinedTerm @exclude(operations: [CREATE]) {
  id: ID @cypher(statement: """RETURN id(this) """) 
  gid: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.gid """)
  gid_url: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.gid_url """)
  identifier: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.identifier """)
  sub_type: String @cypher(statement: """MATCH ()<-[this]-(source) RETURN source.sub_type """)
  _labels: [String] @cypher(statement: "MATCH ()<-[this]-(source) return labels(source)")
}
```

You can disable the other Mutations also if you don't need them. But closing this issue now as expected behaviour.

**Closed by darrellwarde** 2021-08-03 15:57 UTC
Labels: bug report, inbox

**Comment by acmeguy** [comment] 2021-08-03 16:06
Thank you! 

I already disabled the mutations as this is strictly a READ-ONLY API.
Just wanted you to know.
