### ISSUE TITLE
Type with name "BigInt" does not exists after upgrading from 2.1.0

### ISSUE THREAD

**Issue by Kubera2017** [neo4j/graphql#586] opened 2021-11-16 02:37 UTC
**Describe the bug**
I tried to upgrade an existing project from 2.1.0 and got this error: "Type with name "BigInt" does not exists". I tried 2.2.0, 2.3.0 and 2.4.0

**Comment by Kubera2017** [comment] 2021-11-16 03:08
I found the issue, basically it doesn't work now with this syntax:
```
input ExampleInput {
  value: BigInt = 0
}
```
If I remove default value it works
```
input ExampleInput {
  value: BigInt
}
```

**Comment by darrellwarde** [comment] 2021-11-16 11:58
I don't seem to be able to reproduce this @Kubera2017! I'm assuming you're seeing this error on server startup?

**Comment by Kubera2017** [comment] 2021-11-16 14:11
Yes, here is it with blank setup
![Code_DNCMd3F32T](https://user-images.githubusercontent.com/29781060/142000722-ec2f980d-e190-4bb4-bee1-d3792fd5de4d.png)

```
const { Neo4jGraphQL } = require("@neo4j/graphql");
const { ApolloServer, gql } = require("apollo-server");
const neo4j = require("neo4j-driver");

const typeDefs = gql`
    input TestInput {
        id: BigInt = "0"
    }

    type Movie {
        id: BigInt!
    }
`;

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("neo4j", "123")
);

const neoSchema = new Neo4jGraphQL({ typeDefs, driver });

const server = new ApolloServer({
    schema: neoSchema.schema,
});

server.listen().then(({ url }) => {
    console.log(`🚀 Server ready at ${url}`);
});
```

**Comment by darrellwarde** [comment] 2021-11-16 14:23
Weird, I definitely can't produce on my end.

Out of interest, what version of `graphql` do you have installed?

**Comment by Kubera2017** [comment] 2021-11-16 14:39
My steps:
```
npm init
npm i -save @neo4j/graphql
npm i -save apollo-server
npm i -save neo4j-driver
npm i -save graphql
```
For graphql it installs graphql@16.0.1

And run the code above with `node index.js`

**Comment by darrellwarde** [comment] 2021-11-16 14:46
So we don't support `graphql@16.x.x` yet, sadly the version specification in our `peerDependencies` doesn't seem to be working as expected.

Can you please instead install `graphql` using `npm i --save graphql@^15.0.0` and try again?

**Comment by Kubera2017** [comment] 2021-11-16 15:19
I tried now, the same thing
![Code_xnImf9SBFX](https://user-images.githubusercontent.com/29781060/142012868-5f1fb863-74a4-4740-a59e-15284d123ea7.png)

**Comment by angrykoala** [comment] 2021-11-18 17:21
This seems to be related to the last update of graphql-compose@9.0.4 doing some checks. @Kubera2017 Could you try `npm i graphql-compose@9.0.3`  and see if that works?

We will fix this asap, but that should be a valid workaround in the meantime

**Comment by Kubera2017** [comment] 2021-11-18 17:57
@angrykoala Yes, you are right, with `graphql-compose@9.0.3` it works, but `npm i graphql-compose` installs `9.0.4` and the bug appears immediately

**Comment by angrykoala** [comment] 2021-11-18 18:21
@Kubera2017 Until it is fixed on our side, you can manually add `graphql-compose@9.0.3` to your package.json ( `"graphql-compose": "9.0.3"` note the lack of `^`) to ensure that version is installed when you do `npm install`

**Closed** 2021-11-19 11:22 UTC
Labels: bug, inbox, bug report
