### ISSUE TITLE
Invalid cypher when aggregating on connection where

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#2670] opened 2023-01-04 13:59 UTC
given:

```graphql
type Movie {
    title: String
    genres: [Genre!]! @relationship(type: "IN_GENRE", direction: OUT)
}
type Genre {
    name: String
    movies: [Movie!]! @relationship(type: "IN_GENRE", direction: IN)
}
```

and query

```graphql
{
    movies(where: { genresConnection: { node: { moviesAggregate: { count_GT: 10 } } } }) {
        title
    }
}
```

produces the following cypher:

```cypher
MATCH (this:`Movie`)
WHERE size([(this)-[this0:IN_GENRE]->(this1:`Genre`) WHERE var2 = true | 1]) > 0
RETURN this { .actorCount } AS this
```

where `var2` is not defined.

**Comment by neo4j-team-graphql** [comment] 2023-01-04 13:59
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment] 2023-01-04 18:14
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.

**Comment by Andy2003** [comment] 2023-01-11 07:46
This problem also applies to relations:

```graphql
{
    movies(where: { genres: { moviesAggregate: { count_GT: 10 } } }) {
        title
    }
}
```

```cypher
"MATCH (this:`Movie`)
WHERE EXISTS {
    MATCH (this)-[:IN_GENRE]->(this0:`Genre`)
    WHERE var1 = true
}
RETURN this { .title } AS this"
```

**Comment by Liam-Doodson** [comment] 2023-01-19 12:06
I'm reopening this issue as the fix has been reverted due to it's impact on performance

**Closed** 2023-01-24 13:08 UTC
Labels: confirmed, bug report, reopened
