### ISSUE TITLE
Default Values are not set on Where and Options types in the custom query

### ISSUE THREAD

**Issue by magaton** [neo4j/graphql#520] opened 2021-09-30 22:06 UTC
**Describe the bug**
Default Values are not set on `Where` and `Options` types in the custom query

**Type definitions**
```
downline(
  where: ClientWhere = { typeLevel : "All" }
  options: ClientOptions = {sort: [name: ASC]}
): [Client] @cypher(statement: """
MATCH (client: Client) WHERE client.type = $where.type
RETURN {id: client.if, name: client.name, login: client.login, typeLevel: $where.typeLevel} ORDER BY $options.sort
  """)
```

**To Reproduce**

Query
```
query {
  downline (where: {type: "Customer"}, options: {limit: 10}) {
    id
    name
    login
    typeLevel
  }
}
```

`typeLevel` resolves as null, 
`$options.sort` is completely ignored

Moreover, `$options.sort` is ignored also in the case when it is specified in the method call:

```
query {
  downline (where: {type: "Customer"}, options: {sort: [{name: DESC}]}) {
    id
    name
    login
    typeLevel
  }
}
```
does not return clients sorted by name DESC

**Expected behavior**
that default values set on `Where` and `Options` types works
that sort is properly resolved when passed to embedded cypher query inside a custom query type

**System (please complete the following information):**

-   Version: [e.g. @neo4j/graphql@2.2.0]

**Additional context**
There are actually 2 issues in this one:
- default parameter values for Where and Options
- passing @options.sort to embedded cypher

**Comment by darrellwarde** [comment] 2021-10-13 13:44
@magaton, we won't have enough to reproduce and write tests here - can you please provide enough type definitions so that the `downline` query will work as expected?

**Comment by magaton** [comment] 2021-10-15 19:34
First, thank you for investigating `$options.sort` not being properly resolved in cypher for custom query types. This is more important than the rest.

Wrt default values in `where` and `options`, I need to provide `where`, since I always have mandatory arguments, like `login`, so I do not want to get rid of `where`, but to specify default values for arguments inside `where`
The same applies to default sort and limit in `options`

In the deprecated js library, arguments were supplied inline, and I was able to declare the default values like this:
```
downline(login: String!,  typeLevel: String="All")
``` 

and the value 'All' would be passed, although `typeLevel` is not specified in the method call.
```
 {
        downline(login: "c4") {
            id
            name
            level
            typeLevel
        }
    }
```

I have asked on discord and you suggested (I am not quoting you :)) to use 
`ClientWhere = { typeLevels = ["All"] }` syntax.

I think it could be a really useful feature.

Do you have any example of a custom resolver that does anything similar to what you had in mind?

**Comment by darrellwarde** [comment] 2022-01-19 14:53
On reflection of this, this is not a bug because the GraphQL language does not allow this, so I have re-labelled this as a feature request which will help us better plan it in the future. Cheers!

**Comment by darrellwarde** [comment] 2022-09-06 15:14
Closing this as superseded by #499 and #541 which discuss default options for filtering and sorting separately.

**Closed by darrellwarde** 2022-09-06 15:14 UTC
Labels: feature request, auth-2.0
