### ISSUE TITLE
@auth directive how to "OR" between rules

### ISSUE THREAD

**Issue by juan2lv** [neo4j/graphql#634] opened 2021-12-10 04:48 UTC
**Describe the bug**
It say "Each rule is fallen through until a match is found against the corresponding operation. If no match is found, an error is thrown. You can think of rules as a big OR." in the documentation of Neo4j GraphQL Library. But in fact it work as "AND". My code looks like this:

**Type definitions**

```graphql
type Person {
  id: ID @id
  name: String
  email: String
  roles: [String]
}

type Document {
  id: ID @id
  title: String
  owner: Person @relationship(type: "OWN", direction: IN)
}

extend type Document @auth(rules: [{
  where: { owner: { id: "$jwt.sub" }}
}, {
  roles: ["admin"]
}])
```

**To Reproduce**
Then run the following Query...

```graphql
query Documents($options: DocumentOptions) {
  documents(options: $options) {
    _id title
  }
  documentsCount
}
```

**Expected behavior**
I want to allow both owner and admin to have access right. But in fact I can only query using an admin account and comes out results belong to the admin user only. I tried wrapping them with a "OR", then admin user can get all records and normal user still get "Forbidden". With "where" only, everyone can get their own records.

**Screenshots**

**System (please complete the following information):**

-   OS: Windows
-   Version: @neo4j/graphql@2.3.0
-   Node.js version: v14.18.1

**Additional context**

**Comment by Tanner-Scadden** [comment] 2021-12-10 06:47
I believe you'd need to do 

```
extend type Document
    @auth(
      rules: [
        { OR: [{ roles: ["admin"] }, { allow: { owner: { id: "$jwt.sub" } } }] }
      ]
    )
```

This would scope the document to only be operated on by admins or the owner.

**Comment by juan2lv** [comment] 2021-12-13 01:51
> 

I tried. In this case, admin user can get all records and normal user still get "Forbidden"

**Comment by darrellwarde** [comment] 2021-12-13 13:09
Hey @juan2lv, this is a known issue, which is being addressed by @rcbevans in #490.

We just can't quite merge it yet because it needs a few more tests, but we might have to internalise the rest of the work given that this has now been raised a couple of times.

**Comment by juan2lv** [comment] 2021-12-14 02:45
> Hey @juan2lv, this is a known issue, which is being addressed by @rcbevans in #490.
> 
> We just can't quite merge it yet because it needs a few more tests, but we might have to internalise the rest of the work given that this has now been raised a couple of times.

Thanks @darrellwarde, looking forward to the new updates.

**Comment by darrellwarde** [comment] 2021-12-21 17:22
Going to close this as a duplicate of #482, and the fix should be merged shortly after Christmas!

**Closed by darrellwarde** 2021-12-21 17:22 UTC
Labels: bug, inbox

**Comment by binnyFriedman** [comment] 2022-03-09 11:19
Hey, thanks for the great work.
was this fixed and available in a release already?
