### ISSUE TITLE
PopulateBy not accepting async function

### ISSUE THREAD

**Issue by moonthug** [neo4j/graphql#3822] opened 2023-08-22 10:03 UTC
**Describe the bug**
When a `populatedBy` callback function is asyncronous, an error is thrown.

```
PopulatedBy callback 'code' must be of type function
```

**Type definitions**
```
type Recording {
  id: ID! @id(autogenerate: true)
  code: String! @populatedBy(callback: "code", operations: [CREATE])
  name: String!
  description: String!
  ...
}
```

```
const codeCallback: Neo4jGraphQLCallback = async (_parent, _args, context) => {
  const code = await getNextCodeAndIncrement((context.session as Session).user.id, 'Recording');
  return code;
};

const neoSchema = new Neo4jGraphQL({
  typeDefs,
  driver,
  features: {
    populatedBy: {
      callbacks: {
        code: codeCallback
      }
    }
  },
});
```

**To Reproduce**
This is in NextJS 13 (which shouldn't seem to matter?)

**Expected behavior**
The callback _is_ called and works correctly, however, an Error is thrown. The `/api/graphql` endpoint is only accessible in dev mode as it crashed the route in production.

**Screenshots**
Error:

```
- error unhandledRejection: Error: PopulatedBy callback 'code' must be of type function
    at getPopulatedByMeta (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/schema/get-populated-by-meta.js:45:15)
    at obj.fields.reduce.relationFields (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/schema/get-obj-field-meta.js:405:85)
    at Array.reduce (<anonymous>)
    at getObjFieldMeta (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/schema/get-obj-field-meta.js:49:25)
    at eval (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/schema/get-nodes.js:114:61)
    at Array.map (<anonymous>)
    at getNodes (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/schema/get-nodes.js:43:47)
    at makeAugmentedSchema (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/schema/make-augmented-schema.js:153:52)
    at eval (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:295:100)
    at new Promise (<anonymous>)
    at Neo4jGraphQL.generateExecutableSchema (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:278:16)
    at Neo4jGraphQL.getExecutableSchema (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:110:42)
    at Neo4jGraphQL.getSchema (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:106:21)
    at eval (webpack-internal:///(rsc)/./node_modules/@neo4j/graphql-ogm/dist/classes/OGM.js:118:28)
    at new Promise (<anonymous>)
```

**System (please complete the following information):**

* OS: Linux
* Version: @neo4j/graphql@3.24.1
* Node.js version: 18

**Additional context**

**Comment by neo4j-team-graphql** [comment] 2023-08-22 10:03
Many thanks for raising this bug report @moonthug. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment] 2023-08-22 10:03
Many thanks for raising this bug report @moonthug. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by Liam-Doodson** [comment] 2023-08-22 10:54
Hi @moonthug! I've not been able to reproduce your issue. Are you able to try this without using the `Neo4jGraphQLCallback` type in your code as this is not something we export with the library?

**Comment by Liam-Doodson** [comment] 2023-08-22 12:39
I've also just re-read your error message. It looks like you're using the OGM. Is it possible that you've not passed the callback to the OGM as below?

```js
const ogm = new OGM({
  typeDefs,
  driver,
  features: {
    populatedBy: {
      callbacks: {
        code: codeCallback
      }
    }
  },
});
```

The error you're seeing is what I'd expect if this is the case

**Comment by Liam-Doodson** [comment] 2023-08-30 15:37
Hi @moonthug. As I've not been able to reproduce this bug I'm going to close it. If you're still having issues with this, please feel free to re-open this issue and provide code/type definitions that reproduce the issue

**Closed by Liam-Doodson** 2023-08-30 15:37 UTC
Labels: bug report
