### ISSUE TITLE
GraphQL Queries do not return relationship data on custom cypher queries

### ISSUE THREAD

**Issue by jaedag** [neo4j/graphql#227] opened 2021-05-30 08:24 UTC
I've noticed that when I write a graphql query to return a relationship on an object returned from a cypher query, I get `null`.

For example: Here is my Member type definition 

**Type definitions**

```
type Member {
  id: ID! @id
  firstName: String 
  middleName: String
  lastName: String
  email: String
  phoneNumber: String
  whatsappNumber: String
  pictureUrl: String
  gender: Gender @relationship(type: "HAS_GENDER", direction: OUT)
}
```

This is my query definition for townMemberList

```
 townMemberList(id: ID): [Member]
    @cypher(
      statement: """
      MATCH (town:Town {id:$id})
      OPTIONAL MATCH (town)<-[:BELONGS_TO]-(member:Member)
      RETURN member
      """
    )
```

Here is the graphql query  I am currently trying to run 

```
{
  townMemberList(id: "ca1ee77e-07d1-4065-b483-942c62af6bdf") {
    firstName
    lastName
    phoneNumber
    gender {
      gender
    }
  }
}
```

And this is the result I am getting from graphql playground

```
{
  "data": {
    "townMemberList": [
      {
        "firstName": "Kelvin",
        "lastName": "Amieson",
        "phoneNumber": null,
        "gender": null
      },
      {
        "firstName": "Collins",
        "lastName": "Parks",
        "phoneNumber":"0264248277",
        "gender": "02642481234"
      }
]
}
}
```

I get the same response for all my custom cypher queries. I get responses for properties on nodes, but not on their relationships. 

I do not get the same feedback when using the autogenerated queries from the neo4j/graphql library. Using the autogenerated queries, I am able to return the gender property fine.

**System:**

-   OS: macOS
-   Version:  @neo4j/graphql@1.0.1
-   Node.js version: v14.16.0

**Comment by MeetSnowmaker** [comment] 2021-05-30 12:42
It happens because the cypher query you described does not involve the fetching of the other things you are requesting on the graphql side. It could be solved if you write a 'custom' resolver for gender via a conditional OGM call. That way every time you need member and it is not resolved automatically via the generated cypher query that the current library implementation uses, you can tell it to go and fetch it. It could become tedious if you have to write it for every single Type, but considering if you have no automatic nested resolve options, it is the preferred way to implement with the usage of dataloaders for each resolve function. Ideally OGM should be feeded with the info object for every single request that happens in a given number of ticks thus loaded to the same batch and would be resolved by a single cypher statement that is like a giant generated magic wtf.

I usually just write field level resolvers for everything with ctrl c + v as they are more or less the same with different variable names. There is like 4 types of resolvers one for scalars, one for single relations, 1:N relations where you return an array of objects, and one for 1:N relations where you return a pagination supported {cursor, aggregate, nodes[]} object, you just check if they are present in the parent, if not you send them to a dataloader implementation that can resolve them in batches.

It would be a good idea to somehow provide options for generic queries where you can define the search or filter parameters and the returnable type. From there on every time you call that query the library will inject the search or filter statements but also constructs its own info object for nested field resolvers.

As for a use case: the previous grand stack was able to call lucene based text search on indexes generated via search directives in the datamodel (schema actually). Right now I have to write a custom query that will not return anything but the scalar fields by default, and then augment custom resolvers for fields where I want to use them.

**Comment by DomVinyard** [comment] 2021-05-30 17:18
I just posted this issue up on [the discord](https://discord.com/channels/787399249741479977/818578492723036210) - I should've checked here first.

**Comment by litewarp** [comment] 2021-05-30 18:50
Just an FYI, I requested an option for returning all the primitive fields on a queried node in #204. It doesn't solve the waterfall or n+1 issue, but it would certainly help those of us who want to extend the neo4j/graphql schema (as would returning the compiled cypher string)

**Comment by DomVinyard** [comment] 2021-05-30 22:13
@MeetSnowmaker 

> I usually just write field level resolvers for everything with ctrl c + v as they are more or less the same with different variable names. There is like 4 types of resolvers one for scalars, one for single relations, 1:N relations where you return an array of objects, and one for 1:N relations where you return a pagination supported {cursor, aggregate, nodes[]} object, you just check if they are present in the parent, if not you send them to a dataloader implementation that can resolve them in batches

Do you have any code in a public repo with this pattern by any chance?

**Comment by DomVinyard** [comment] 2021-06-01 19:49
Response to this issue on the Discord was

@darrell.neo:
> Honestly, right now the @cypher is performing as we’d expect it to - it’s down to the end user to return what they need in their queries. I believe the old library worked this way as well (happy to be proven wrong there), so surprised to hear this would be a blocker to migration. Changing this behaviour is more of a new feature than a bug fix, so may not find its way to the surface for a while.

The old library has this "Translate GraphQL to Cypher" section in the docs (https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/docs/neo4j-graphql-js.md) which handles our use case here, perhaps there is a similar solution in the new library which I have missed?

If the team has no plans to replicate this functionality from the old libraries, I guess the questions I'd like to ask are:

1. Is this recognised as a regression?
2. Does the team have a recommended solution to achieve the same functionality?

**Comment by michaeldgraham** [comment] 2021-06-02 00:36
I believe that your questions are sound, @DomVinyard, and I think we all appreciate you asking them. 

The apparent regressions and possible resolutions have remained multifarious and disconcerting. At this point, I have come to regret not prioritizing a specification of the augmentation and translation logic in neo4j-graphql-js independent from its code, which eventually became rather disorganized. I am sorry for this because it may have helped us all to better keep track of these differences, perhaps enabling the GraphQL Team to better situation the new library for migration.

I do believe it to be unfortunate that it seems we must wait longer to be able to use these languages together in a manner sufficient for our existing needs and interests. It was not necessary to move so quickly on this library before migration was reasonably approachable. I quit Neo4j because I could not prevent this process that we see unfolding now. But sincerely, despite my concerns and motivations, I have wanted to make maximally certain that I do not significantly interfere with the perceptions or activities involved with this new, official library for GraphQL integration.

I believe that the context of our collectively implementing a library that would remain entirely open-source, yet not likely officially supported by Neo4j, will make itself clear in time if it becomes necessary. But in the open-source spirit, I have learned that despite circumstances, I should do as much as I can to help with @neo4j/graphql. I have been waiting to see if that is the general sentiment, and it seems to be. So if I can help you in any way possible with either library, do please let me know. If the GraphQL Team at Neo4j would like my help with this issue - I am certainly still here and paying attention. <3

**Comment by DomVinyard** [comment] 2021-06-02 07:45
Honestly @michaeldgraham, if you and the team could find a path forward to enable that, it would give us a ton of confidence.

From our perspective:

1. An Aura release introduced a [breaking change in our production environment](https://github.com/neo4j-graphql/neo4j-graphql-js/issues/612) due to an incompatibility with the old library. Our service was down for ~12 hours waiting on the patch. 
2. Having understood this to mean that migration was now non-optional we began migration
3. Unable to migrate due to this issue - no documentation around how to migrate this functionality, no working code samples anywhere. (we have actually found a workaround overnight using OGM selectionSet - but it is not an intuitive solution at all).
4. Insufficient communication from the team honestly, I do appreciate darrell.neo's input, but I would be lying if I felt like the conversation had any sense of urgency or concern

The old library was always rock solid in my experience, never encountered a single issue. And now, since the breaking change in prod, we have been having serious discussions along the lines of "the old library is unmaintained, the new library is not ready, we wouldn't be having these issues with Prisma, etc". 

Our confidence in this stack is seriously shaken.

I have no agenda here, I can read between the lines and see there are clearly some politics. Honestly I just want a solution that doesn't break in production and is maintained going forward. I'm happy to do my part as a good citizen to help report bugs, but knowing that the original developer was back in the conversation would definitely reassure us.

**Comment by danstarns** [comment] 2021-06-02 11:41
The desired behaviour works in `neo4j-graphql-js` and I think it would be neat to support the same here. Given the following Schema: 

```graphql
type User {
    id: String
    friends: [User] @cypher(
        statement: """
        MATCH (this)-[]-(friend:User)
        RETURN friend
        """
    )
}

type Query {
    me: User @cypher(
        statement: """
        MATCH (user:User { id:  1 })
        RETURN user
        """
    )
}
```

And following query: 

```graphql
{
  me {
    id
    friends {
      id
    }
  }
}
```

neo4j-graphql-js produces 

```
WITH apoc.cypher.runFirstColumn("MATCH (user:User)
RETURN user", {offset:$offset, first:$first}, True) AS x UNWIND x AS `user` RETURN `user` { .id ,friends: [ user_friends IN apoc.cypher.runFirstColumn("MATCH (this)-[]-(friend:User)
RETURN friend", {this: user}, true) | user_friends { .id }] } AS `user`
```

Whereas this implementation only produces: 

```
MATCH (user:User)
RETURN user
```

From my point of view, this is simply an oversight in the recursion and projection of the custom cypher and we need to wrap the custom cypher inside runFirstColumn. What are your thoughts @darrellwarde ?

**Comment by darrellwarde** [comment] 2021-06-02 12:21
Definitely some valid complaints here, one of which @danstarns has described well above, but I do think we've now actually split out into two discreet issues.

The `@cypher` directive is an interesting one for me. I see it as "what you see is what you get" - if you ran both of those Cypher queries against a database using Neo4j Browser or Cypher Shell, you wouldn't get any of the automatic recursion down the graph. But at the same time, when dealing with GraphQL, I would expect to be able to recurse down! I think, as a GraphQL library, that this needs addressing. Personally, I would love to try and see if we can achieve this using subqueries instead of `apoc.cypher.runFirstColumn` to avoid building up even more technical debt in APOC dependencies. 

@DomVinyard, in your comment before last, you brought up the `neo4jgraphql` function in the old library, which I consider to be a different feature. This allowed you to do _post-processing_ on the results returned from the database. We have not included this functionality because we believe that the behaviour can be achieved using the OGM, but taking this approach, any processing is done in the Cypher generated by the OGM, which will result in a massive performance improvement when dealing with large returns. In my opinion, the paradigm shift from a `neo4jgraphql` function to the OGM is worthwhile trade-off for the improved performance. If you feel like the developer experience with the OGM is sub-optimal, then please raise an issue describing what you would like to be improved. If after reading this, you still believe there is a place for a `neo4jgraphql` function, then could you please raise a regression issue highlighting this? That will allow for this thread to continue, addressing the potential for relationships to be automatically projected whilst using a custom Cypher directive, and we can continue conversations regarding a `neo4jgraphql` function elsewhere. 

Moving on to a couple of side notes... On your point @DomVinyard regarding communication from the team, I would just like to point out that we are a small team of two who are currently juggling monitoring GitHub, Discord, internal queries and customer queries, at the same time as developing new features and bug fixes in the library, as well as other things! As much as I love the community in the Discord channel, we do approach it with a best endeavours basis when it is busy, and it is as much of a platform for the community to help each other. Please remember that if you are a Neo4j customer, there are support channels which you can go down for official support with the GraphQL Library.

Finally, we welcome _anyone_ to collaborate on this library, whether they are one of the developers of the library it has replaced or someone completely new to Neo4j and GraphQL. We welcome discussions on issues such as this, and code contributions leading to pull requests. We just ask that issues are fully discussed and solutions agreed with the team before diving into the codebase, to ensure that solutions fit into our roadmap and vision for this product.

**Comment by DomVinyard** [comment] 2021-06-02 13:35
Thanks for the responses here, really great to see.

I understand now I was a little confused in conflating these two issues. They come from trying to solve a single use case which I'll try to explain. 

We use the [Viewer Pattern](https://medium.com/workflowgen/graphql-schema-design-the-viewer-field-aeabfacffe72) extensively throughout our codebase, we basically we have a `me { }` object at the root of every query. With the old library we were using the (now depricated) `neo4jgraphql` function to inject the jwt and then return a User which could then be queried to any depth of recursion. Using the new library I see [from the docs](https://neo4j.com/docs/graphql-manual/current/type-definitions/cypher/) that we **should** just be able to use `$auth.jwt.sub` directly in a @cypher statement but then we are stuck without relationships. 

This is the cause of the conflation, two ways to solve a single use case. I see that my confusion led to some miscommunication here and I take full responsibility for that.

I don't have nearly enough experience to know which of these two 'solutions' is best but from a user perspective (other than @darrellwarde probably knows what he's talking about in advocating the latter), regardless I just need some way to make all of our `Me` queries come back to life, as it stands now we _still_ don't have a way to migrate. (The `selectionSet` approach in my comment above gets us some of the way but is not usable in that state). 

> just like to point out that we are a small team of two who are currently juggling monitoring GitHub, Discord, internal queries and customer queries, at the same time as developing new features and bug fixes in the library, as well as other things!

Yes, I do understand the pressure you're under. I would've happily used the old library for months (until this new one felt sufficiently mature) if it wasn't for the Aura bug/incompatibility last week which caused us prod outage, if it wasn't for that you'd have never heard from me. We still love Neo, goes without saying, but that really should be treated like a serious incident. 

> Finally, we welcome anyone to collaborate on this library

Glad to be part of the community, will try to help where we can 🙂

**Comment by darrellwarde** [comment] 2021-06-02 15:41
It's perfectly viable that the OGM approach I described isn't as user friendly as it needs to be at the moment, as you have perhaps encountered whilst trying to use the selection set from your query.

I can definitely see this as a candidate for work in our next dev phase, however, we're pretty maxed out in the lead up to this year's NODES conference on 17th June.

However, would love to hear some _ideal_ solutions for this, using the `@cypher` directive or otherwise, and we can use that as inspiration as we shape and plan this work. 🙂

**Comment by DomVinyard** [comment] 2021-06-03 10:33
> OGM approach I described isn't as user friendly as it needs to be

I think with sufficient documentation and some code samples it would be fine, but we had to go diving into the internals of Apollo to learn how to get the current query as a string from a resolver and all that fun stuff. 

Happy to let someone else raise the ticket for `OGM refinement vs neo4jgraphql function`, etc, I feel like relationships being automatically projected would cover our use case here perfectly. 

> I would love to try and see if we can achieve this using subqueries instead of apoc.cypher.runFirstColumn to avoid building up even more technical debt in APOC dependencies

Can't wait to see what you come up with 😃

**Comment by mathix420** [comment] 2021-06-24 16:24
If someone need a temporary fix, this should help
```
npm install 'https://gitpkg.now.sh/mathix420/graphql/packages/graphql?master&scripts.postinstall=npm%20i%20--ignore-scripts%20%26%26%20npm%20run%20build%3Aclean'
```
It's based on https://github.com/neo4j/graphql/pull/251, I have made small changes in config files in order to make it work with https://gitpkg.now.sh/

This could also help finding bugs in this this PR.

**Closed** 2021-06-30 13:47 UTC
Labels: bug report, inbox

**Comment by fnfbraga** [comment] 2021-08-25 16:35
we had the need to find a solution for the replacement of the exposed neo4jgraphql function.
 we used it in resolvers like this
 
`
Company: async (obj: any, args: any, context: { user: User }, info: GraphQLResolveInfo) => {
// run some business logic
	return neo4jgraphql(obj, args, context as any, info);
},
`

this was convenient because we did not have to write queries and could run our business logic passing the query execution to that function exposed by the previous lib

With v2 and its introduction of compatible selection sets we believe we found a solution for this and created a generic function that looks more or less like this:

` 
import { GraphQLResolveInfo, print } from "graphql";
import { ogm } from "../middlewares/apollo-server";
import startUpper from "./start-upper";

/**
 *
 * Translates a graphql query into a neo4j/graphql query using neo4j/graphql-ogm
 *
 * @param args graphql query args
 * @param info GraphQLResolveInfo
 * @author Lyfegen HealthTech AG
 */

const runNeo4jGqlQuery = async (args: { where?: any; options?: any }, info: GraphQLResolveInfo) => {
	const nodeLabel = startUpper(info.fieldName.slice(0, -1));
	const type = ogm.model(nodeLabel);
	const operationStr = Object.entries(info.fragments).reduce(
		(operationStr, fragment) =>
			operationStr.replace(`...${fragment[0]}`, print(info.fragments[fragment[0]].selectionSet).substring(1).slice(0, -1)),
		print(info.operation.selectionSet)
	);

	const parentHasArgs = Object.keys(args).length > 0;
	const where = parentHasArgs && args.where;
	const options = parentHasArgs && args.options;
	const selectionSet = !parentHasArgs
		? operationStr.split(nodeLabel.toLowerCase() + "s")[1].slice(0, -1)
		: operationStr.substring(operationStr.indexOf(")") + 1).slice(0, -1);
	return await type.find({ where, selectionSet, options });
};

export default runNeo4jGqlQuery;
`

and can use it just like this:

`
companies: async (obj: any, args: any, context: { user: User }, info: GraphQLResolveInfo) => {
       // run some business logic
	return runNeo4jGqlQuery(args, info);
},
`

thank you to the neo4j team for this excelent library

**Comment by sim51** [comment] 2021-11-08 15:21
For people that read this issue, and want to mimic the behaviour of the old `neo4jgraphql`, the use of the `runNeo4jGqlQuery`  function as describe above is good start. (FYI, there is an issue with fragment that uses fragment, ...  you can check the version [here](https://gist.github.com/sim51/0ec87ae5f3992fc4e557139411796ddf)  to see how to solve it)

But should be aware that : 
- you probably have to split your typeDefs schema in two : one for OGM, and a complement for your graphQL schema (mainly query & mutation)
 - neo4j-ogm don't care of the @auth directive on your schema, so you can leaks data

The solution I found for my project is the following : 

Create a query with the cypher directive where you will use `cypherParams`. Example :

```
_getCompany: Company @cypher(statement: "MATCH (n:Company {id: $cypherParams.id} ) RETURN n")
```

This query will be result you want, and will check all the @auth directive because you are using the neo4j-graphql stack.
`cypherParams` are part of the neo4j-graphql lib : https://neo4j.com/docs/graphql-manual/current/type-definitions/cypher/#_cypherparams

NOTE: this query will be part of the exposed schema, but no-one will be able to use it, because users can't set the context (ie. the cypherParams), only the server can do it.

Then in your custom resolver, you have to delegate the result to this query, thanks to `graph-tools`  :

```
import { delegateToSchema } from "@graphql-tools/delegate";

...

Query: {
  company: async (obj: any, args: any, context: { user: User }, info: GraphQLResolveInfo) => {
       // do what you want here !  
       
     // Calling _getCompany  query with the good cypherParams
      const company = await delegateToSchema({
        schema: info.schema,
        operation: "query",
        fieldName: "_getCompany",
        context: { ...ctx, cypherParams: { id: params.id } },
        info: info,
      });
       
	return company;
  },
 ...
 }
...
```

Last point, if like me, you want to compute the data only for a subfield, it's also possible : 

```
import { delegateToSchema } from "@graphql-tools/delegate";
import { ExtractField } from "@graphql-tools/wrap";
...

Query: {
  company: async (obj: any, args: any, context: { user: User }, info: GraphQLResolveInfo) => {
       // do what you want here !  
       
     // Calling _getCompany  query with the good cypherParams
      const company = await delegateToSchema({
        schema: info.schema,
        operation: "query",
        fieldName: "_getCompany",
        context: { ...ctx, cypherParams: { id: params.id } },
        info: info,
        transforms: [
           // take the subfield `company` of this query and put it as root for delegate query
          new ExtractField({
            from: ["_getCompany", "company"],
            to: ["_getCompany"],
          }),
        ],
      });
       
	return { isValid:true,  company };
  },
 ...
 }
...
```
