### ISSUE TITLE
Make items within arrays required

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#809] opened 2022-01-18 13:39 UTC
All array items should be non-nullable.

This is to track issues with array fields currently allowing `null` values:

- [x] `AND` and `OR` in unions where [ref](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/schema/connect-or-create-unions.test.ts#L110-L111)
- [x] Sorting fields [ref](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/schema/aggregations.test.ts#L176)
- [x] All `_IN_ clauses in the where type [ref](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/schema/aggregations.test.ts#L214)

**Comment by neo4j-team-graphql** [comment] 2022-01-25 11:17
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment] 2022-01-25 14:45
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!

**Comment by darrellwarde** [comment] 2022-01-25 16:28
First two fixed in #874, last one intentional because it allows you to check "value is either this value or unset on the node". Perhaps this could be changed for non-nullable fields.

**Closed** 2022-01-28 16:29 UTC
Labels: confirmed, bug report, high priority

**Comment by Andy2003** [comment] 2022-03-25 16:19
@darrellwarde I found another occurence of nullabel array items: https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/schema/comments.test.ts#L939
