### ISSUE TITLE
Being able to delete nodes with a specific connectionAggregate count in a nested delete operation

### ISSUE THREAD

**Issue by teenkevo** [neo4j/graphql#1640] opened 2022-06-26 01:49 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Let's say 
1. I have an application database which has multiple organizations. 
2. Each organization has its own admins. 
3. An admin can belong to multiple organizations as shown in the figure below.  

![image](https://user-images.githubusercontent.com/46814008/175792832-0371817b-e476-4524-94e4-448200df2d6c.png)

While deleting an organization, I would like to delete the organization together with its administrators as long as they don't participate in any other organization. 

In the mutation below, I try to delete the organization Google together with its admin(un named node). The other admins connected to Google (Mugukey and Mugumya) should not be deleted but only disconnected from Google. 

**What happens**: Only the organization node Google gets deleted, and 3 relationships (1 from each of the admins)
**What was expected**: Deletion of the organization Google, deletion of the unnamed admin node, and deletion of the 3 relationships(1 from each of the admins).

Not sure if this is a bug but the feature being requested is for this functionality to work.

_Query_
```graphql
mutation DeleteOrganizations($where: OrganizationWhere, $delete: OrganizationDeleteInput) {
  deleteOrganizations(where: $where, delete: $delete) {
    nodesDeleted
    relationshipsDeleted
  }
}
```
_Variables_
```graphql
{
  "where": {
    "title": "Google"
  },
  "delete": {
    "admins": [
      {
        "where": {
          "node": {
            "organizationsAggregate": {
              "count": 1
            }
          }
        }
      }
    ]
  }
}
```
**Describe alternatives you've considered**
I first delete all the admins connected to only the organization Google. 

_Query_
```graphql
mutation Mutation($where: AdminWhere) {
  deleteAdmins(where: $where) {
    nodesDeleted
    relationshipsDeleted
  }
}
```
_Variables_
```graphql

  "where": {
    "organizationsAggregate": {
      "count": 1
    },
    "organizations_ALL": {
      "title": "Google"
    }
  }
}
```

and then I delete the organization
_Query_
```graphql
mutation DeleteOrganizations($where: OrganizationWhere) {
  deleteOrganizations(where: $where) {
    nodesDeleted
    relationshipsDeleted
  }
}
```
_Variables_
```graphql
{
  "where": {
    "title": "Google"
  }
}
```

**Additional context**
None

**Comment by angrykoala** [comment] 2022-09-30 10:59
Hi @teenkevo 
This appears to be fixed since version `3.7.0` follows some general changes to the cypher queries.

I'll include some tests to ensure that a regression does not happen on this, and I'll close this as fixed now

**Closed by angrykoala** 2022-09-30 10:59 UTC
Labels: feature request
