### ISSUE TITLE
@authentication doesn't work

### ISSUE THREAD

**Issue by YashvardhanKumar** [neo4j/graphql#5214] opened 2024-06-07 10:26 UTC
**Describe the bug**
I can just use global authentication on schema but cannot use it for specific object like this 

`extend schema @authentication`

**Type definitions**
```['graphql']
type User
    @authorization(
      filter: [
        {
          where: {
            node: {
              id: "$jwt.user.id"
              email: "$jwt.user.email"
            }
          }
        }
      ]
    ) 
{
    id: String! 
    name: String! @authentication
    email: String! 
    hash: String! @authentication
    username: String! 
    dob: DateTime @authentication
    posts: [Post!]!
      @relationship(
        type: "POSTED_BY"
        direction: OUT
      ) @authentication
    authorOfComments: [Comment!]!
      @relationship(
        type: "COMMENTED_BY"
        direction: OUT
      )
  }
```

**To Reproduce**
```
 @neo4j/graphql:auth JWSSignatureVerificationFailed: signature verification failed
    at flattenedVerify 
  code: 'ERR_JWS_SIGNATURE_VERIFICATION_FAILED'
} +36ms
  @neo4j/graphql:auth request not authenticated +0ms
  @neo4j/graphql:execution executing cypher +11m
  @neo4j/graphql:execution CALL dbms.components() YIELD versions, edition UNWIND versions AS version RETURN version, edition +0ms
  @neo4j/graphql:execution cypher params: {} +0ms
  @neo4j/graphql:translate ReadOperation
  @neo4j/graphql:translate |──── NodeSelection
  @neo4j/graphql:translate |──── AttributeField <id>
  @neo4j/graphql:translate |──── AttributeField <email>
  @neo4j/graphql:translate |──── AttributeField <hash> +0ms
  @neo4j/graphql:execution executing cypher +31ms
  @neo4j/graphql:execution MATCH (this:User)
  @neo4j/graphql:execution RETURN this { .id, .email, .hash } AS this +0ms
  @neo4j/graphql:execution cypher params: {} +0ms
  @neo4j/graphql:execution Execute successful, received 1 records +0ms

```

**Expected behavior**
I wanted to get only few fields when user isn't authenicated

**Screenshots**

**System :**

* OS: MacOS
* Version: [@neo4j/graphql@5.4.2]
* Node.js version: [22.2.0]

**Comment by neo4j-team-graphql** [comment] 2024-06-07 10:27
Many thanks for raising this bug report @YashvardhanKumar. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by MacondoExpress** [comment] 2024-06-07 11:14
Hi @YashvardhanKumar,
Sorry, I'm not sure what to follow, the issue here seems to be an invalid token.
I don't have details on the query you're trying but from the Tree produced it seems that you have tried to access the `hash` field that requires `@authentication`, but even without accessing the `hash` field a valid token would have been required to perform the `@authorization` defined for the type `User`, to allow to perform specific rule for unauthenticated users you can define there the `requireAuthentication` flag on the `@authorization` rule as explained here https://neo4j.com/docs/graphql/current/security/authorization/#_authorization_without_authentication.
I'm going to close the issue as it seems to me that it works as intended, please reopen the issue with newer details in case is not.

**Closed as not planned by MacondoExpress** 2024-06-07 11:14 UTC
Labels: bug

**Comment by YashvardhanKumar** [comment] 2024-06-07 11:38
query Users {
    users {
        id
        email
        hash
    }
}

**Comment by YashvardhanKumar** [comment] 2024-06-07 11:39
type JwtPayload @jwt {
    id: String! @jwtClaim(path: "user.id")
    email: String! @jwtClaim(path: "user.email")
  }
  ```

**Comment by YashvardhanKumar** [comment] 2024-06-07 11:42
```
  type JwtPayload @jwt {
    id: String! @jwtClaim(path: "user.id")
    email: String! @jwtClaim(path: "user.email")
  }
  ```
  
  This is what JWTPayload i have
  i have used the following during the initialization of the Neo4j
  
  ```
  export const gqlProviderFactory = async () => {
  const {
    NEO4J_URI,
    NEO4J_USERNAME,
    NEO4J_PASSWORD,
  } = process.env;

  const driver = neo4j.driver(
    NEO4J_URI,
    neo4j.auth.basic(
      NEO4J_USERNAME,
      NEO4J_PASSWORD,
    ),
  );

  const neoSchema = new OGM({
    typeDefs,
    driver,
    database: 'neo4j',
    debug: true,
    features: {
      authorization: {
        key: {
          url: "http://localhost:3000/.well-known/jwks.json"
        },
      }
    }
  });

  await neoSchema.init();

  await neoSchema.assertIndexesAndConstraints({
    options: { create: true },
  });
  const schema = neoSchema.schema;

  return {
    playground: true,
    schema,
    context: async ({ req }) => ({
      token: req.headers.authorization,
      sessionConfig: { database: 'neo4j' },
    }),
  };
};
  ```
  
  I am trying the following query on User but instead of Unauthorized and unauthenticated error on wrong jwt, it is displaying the data even after @authentication is added
  
  ```
  query Users {
    users {
        id
        email
        hash
    }
}

  ```

**Comment by darrellwarde** [comment] 2024-06-07 12:42
@YashvardhanKumar, the OGM does not support authentication/authorization, which is why this is not working. The OGM is assumed to be running in a "controlled environment", so you will need to deal with this yourself if you want this to work. Sorry!
