### ISSUE TITLE
Sort by string length

### ISSUE THREAD

**Issue by Liam-Doodson** [neo4j/graphql#2841] opened 2023-02-06 13:20 UTC
**Describe the solution you'd like**

For the following type definition:
```gql
type User {
    name: String!
}
```

I'd like to be able to sort by the length of the users name:

e.g:

```gql
query {
    users(options: { sort: { name_LENGTH: ASC } }) {
        name
    }
}
```

OR

```gql
query {
    users(options: { sort: { name: { length: ASC } } }) {
        name
    }
}
```

**Comment by darrellwarde** [comment] 2024-02-21 13:55
Alternative proposal:

```gql
query {
    users(options: { sort: { name: LENGTH_ASC } }) {
        name
    }
}
```

**Comment by darrellwarde** [comment] 2024-11-26 13:43
Duplicate of #1156.

**Closed by darrellwarde** 2024-11-26 13:43 UTC
Labels: enhancement
