### ISSUE TITLE
Database Mapping doesn't work for multiple node labels

### ISSUE THREAD

**Issue by biziloehnert** [neo4j/graphql#2979] opened 2023-03-06 08:58 UTC
### Type definitions

```GraphQL
type Animal @node(labels: ["Dog", "Cat"]) {
    name: String!
}
```

### Test data

```Shell
CREATE (:Dog {name:"bello"}), (:Cat {name: "susi"})
```

### Steps to reproduce

1. provide above's type definition
2. start apollo server
3. query for animals

### What happened

In the documentation of [neo4j/graphql](https://neo4j.com/docs/graphql-manual/current/type-definitions/database-mapping/#_labels) you write that for multiple labels the following cypher query is executed: 
`MATCH (this:Dog:Cat)
RETURN this { .name } as this` 
But apparently this doesn't return the nodes with labels "Dog" and "Cat", the Cypher that would do this would rather look like this: 
`MATCH (this)
WHERE this:Dog OR this:Cat
RETURN this { .name } as this` 

### Version

3.17.0

### Database version

4.4.11

**Comment by neo4j-team-graphql** [comment] 2023-03-06 08:59
Many thanks for raising this bug report @biziloehnert. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment] 2023-03-06 12:50
Hi @biziloehnert, thanks for raising this bug report.

The correct cypher here would be:
```
MATCH (this:`Dog`|`Cat`)
RETURN this { .name } AS this
```
yet that is not valid syntax for any 4.X Neo4j database. The support for this [OR expression](https://neo4j.com/docs/cypher-manual/current/clauses/match/#label-expression-match-or-expression) only got added in Neo4j 5.X.
As you are pointing out correctly, the cypher should therefore be:
```
MATCH (this) WHERE this:Dog OR this:Cat RETURN this { .name } as this
```
which is supported by all 4.X and 5.x Neo4j versions.

**Comment by darrellwarde** [comment] 2023-03-06 14:07
However, this is not the intended behaviour of the library - `labels` implies that _ALL_ of the labels are present on the node, not any of them. So the library is behaving as intended in this case.

This seems to me to be more of a use case for Interface types in GraphQL.

**Comment by biziloehnert** [comment] 2023-03-07 09:10
I see, thank you! I tried to solve this problem with interface types, but in the documentation you write that 
> The Neo4j GraphQL Library supports the use of interfaces on relationship fields.

And in order to implement the above functionality it would probably be necessary to support interfaces also on nodes (without relationships), e.g.: 
```
interface Animal {
   name: String!
}
type Dog implements Animal{
    name: String!
} 
type Cat implements Animal{
    name: String!
}
type Query {
    animals: [Animal]
}
```
I found a similar [example query](https://www.apollographql.com/docs/apollo-server/schema/unions-interfaces/#interface-type) in the Apollo documentation. Is there a way of solving these kind of queries with the neo4j/graphql library?

**Comment by darrellwarde** [comment] 2023-03-07 10:25
Sadly, at the moment we don't generate root-level Interface queries. This is on our roadmap to look at very soon in #146, but I'm afraid until then, there isn't an easy way around this! Going to close this as it will be fulfilled elsewhere.

**Closed by darrellwarde** 2023-03-07 10:25 UTC
Labels: confirmed, bug report
