### ISSUE TITLE
Attributes get lost when calling a field multiple times using aliases

### ISSUE THREAD

**Issue by acmeguy** [neo4j/graphql#350] opened 2021-07-22 11:17 UTC
**Describe the bug**
Only the last set of parameters is used when the same field is called multiple time using aliases.

**Type definitions**
type AnyThing {
    value (some_value: String!): String @cypher(statement: """RETURN $some_value""")
}

**To Reproduce**
Run the following query:
```
query {
  AnyThing(label: "Country") {
    A_val: value(some_value: "A")
    B_val: value(some_value: "B")
    C_val: value(some_value: "C")
  }
}
```
See error in the returned set:
```
  "data": {
    "AnyThing": [
      {
        "A_val": "C",
        "B_val": "C",
        "C_val": "C"
      },
]}
```

**Expected behavior**
Should return this:
```
  "data": {
    "AnyThing": [
      {
        "A_val": "A",
        "B_val": "B",
        "C_val": "C"
      },
]}
```
-   OS: [e.g. Linux]
-   Version: ^1.2.2
-   Node.js version: 14.16.0

**Comment by dmoree** [comment] 2021-07-23 23:15
@danstarns While the example above is using the `@cypher` directive, this issue persists even with `@relationship` fields. This may ultimately be related to how `@neo4j/graphql` deals with aliased fields.

Below is a reproduction based on the `neo-push` example that adds a `flagged` field to a `Comment`.

#### To Reproduce

1. Clone repository
```
git clone https://github.com/dmoree/neo4j-graphql-issue-350.git
```
2. Seed and start server
```
cd neo4j-graphql-issue-350 && yarn install && yarn seed && yarn start
```
3. Run each `query` in GraphiQL at `http://localhost:4000/graphql` (or as defined in `.env`)
##### Flagged
```graphql
query PostsWithFlaggedComments {
  posts {
    comments(where: { flagged: true }) {
      id
      flagged
    }
  }
}
```
```
{
  "data": {
    "posts": [
      {
        "comments": [
          {
            "id": "163a5bb0-ee16-4cf2-807d-84586f926c2d",
            "flagged": true
          }
        ]
      }
    ]
  }
}
```
##### Unflagged
```graphql
query PostsWithUnflaggedComments {
  posts {
    comments(where: { flagged: false }) {
      id
      flagged
    }
  }
}
```
```
{
  "data": {
    "posts": [
      {
        "comments": [
          {
            "id": "11ceb53d-0075-4f95-b3f3-cceb2d66aa0d",
            "flagged": false
          },
          {
            "id": "ad3e5b41-2e92-4fcd-9ad8-e8b1318ade71",
            "flagged": false
          }
        ]
      }
    ]
  }
}
```
##### Both
###### flagged last
```graphql
query PostsWithUnflaggedAndFlaggedComments {
  posts {
    unflaggedComments: comments(where: { flagged: false }) {
      id
      flagged
    }
    flaggedComments: comments(where: { flagged: true }) {
      id
      flagged
    }
  }
}
```
```
{
  "data": {
    "posts": [
      {
        "unflaggedComments": [
          {
            "id": "163a5bb0-ee16-4cf2-807d-84586f926c2d",
            "flagged": true
          }
        ],
        "flaggedComments": [
          {
            "id": "163a5bb0-ee16-4cf2-807d-84586f926c2d",
            "flagged": true
          }
        ]
      }
    ]
  }
}
```
###### unflagged last
```graphql
query PostsWithFlaggedAndUnflaggedComments {
  posts {
    flaggedComments: comments(where: { flagged: true }) {
      id
      flagged
    }
    unflaggedComments: comments(where: { flagged: false }) {
      id
      flagged
    }
  }
}
```
```
{
  "data": {
    "posts": [
      {
        "flaggedComments": [
          {
            "id": "11ceb53d-0075-4f95-b3f3-cceb2d66aa0d",
            "flagged": false
          },
          {
            "id": "ad3e5b41-2e92-4fcd-9ad8-e8b1318ade71",
            "flagged": false
          }
        ],
        "unflaggedComments": [
          {
            "id": "11ceb53d-0075-4f95-b3f3-cceb2d66aa0d",
            "flagged": false
          },
          {
            "id": "ad3e5b41-2e92-4fcd-9ad8-e8b1318ade71",
            "flagged": false
          }
        ]
      }
    ]
  }
}
```

Notice that a `query` with both flagged and unflagged returns the same array for both fields. The array that is returned depends on how `flagged` was defined last; _i.e_ if `flagged: true` is defined last, the array of flagged comments is returned and if `flagged: false` is defined last, the array of unflagged comments is returned.

#### Additional Context
Debugger output for `PostWithFlaggedAndUnflaggedComments`:
```
@neo4j/graphql:execute Execute successful, received 1 records +3ms
  @neo4j/graphql:graphql Incoming GraphQL:
Query:
query PostsWithFlaggedAndUnflaggedComments {
  posts {
    flaggedComments: comments(where: {flagged: true}) {
      id
      flagged
    }
    unflaggedComments: comments(where: {flagged: false}) {
      id
      flagged
    }
  }
}
Variables:
{} +6m
  @neo4j/graphql:auth Could not get .authorization, .Authorization or .cookies.token from req +6m
  @neo4j/graphql:execute About to execute Cypher:
Cypher:
MATCH (this:Post)
RETURN this { comments: [ (this)-[:HAS_COMMENT]->(this_comments:Comment)  WHERE this_comments.flagged = $this_comments_flagged | this_comments { .id, .flagged } ], comments: [ (this)-[:HAS_COMMENT]->(this_comments:Comment)  WHERE this_comments.flagged = $this_comments_flagged | this_comments { .id, .flagged } ] } as this
Params:
{
  "this_comments_flagged": false
} +6m
  @neo4j/graphql:execute Execute successful, received 1 records +8ms
```

**Comment by dmoree** [comment] 2021-07-26 09:32
As suspected, `@neo4j/graphql` currently doesn't deal with aliases correctly. This can be seen with the debugger output above where the projection uses the field name `comments` as opposed to the aliased name `flaggedComments` and `unflaggedComments` and by doing so overwrites attributes. When this is ultimately executed by `graphql` it encounters the aliased name `flaggedComments`, does not find a resolver on `Post` corresponding to `flaggedComments` and defaults to the resolver for the field name `comments`.

This happens to align because the projection in `translate` actually uses the field name rather than using the alias. This appears to work when there is only one alias per field in a query. But in the case where a query aliases a field multiple times, the translate function fails (see above) and produces only one field corresponding to the field name, while the graphql execution falls back to the default resolver in every case the aliased field is used. This produces the bug seen above where the last attribute is used due to the translation error.

I have created a pull request #359  with a possible fix for this issue.

**Closed** 2021-07-28 07:55 UTC
Labels: bug report, inbox

**Comment by acmeguy** [comment] 2021-07-28 08:06
Thank you all for addressing this so promptly.
