### ISSUE TITLE
Global schema configuration not working

### ISSUE THREAD

**Issue by eriklueth** [neo4j/graphql#4157] opened 2023-10-18 15:01 UTC
**Describe the bug**
In your [Global schema configuration Docs](https://neo4j.com/docs/graphql/current/schema-configuration/global-configuration/) you describe that all queries and mutations can be turned of via:

```
  gql`
    extend schema
      @query(read: false, aggregate: false)
      @mutation(operations: [])
  `,
```
When I add this to our schema nothing happens and all queries and mutations are still there. I think we have added it correctly since when I have some @query or @mutation still added to some individual type we get the error:

```
  GraphQLError: Invalid directive usage: Directive @mutation can only be used in one location: either schema or type.
```

I would expect that adding the extend schema stuff it will turn off all autogenerated queries or mutations and just the custom queries and mutations should be shown, but it still shows everything.

**Comment by neo4j-team-graphql** [comment] 2023-10-18 15:01
Many thanks for raising this bug report @eriklueth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment] 2023-10-20 10:09
@eriklueth, any update on the above?

**Comment by eriklueth** [comment] 2023-10-21 17:56
Hey @darrellwarde, 
Sorry for not providing better reproductions in the past... 
I finally had the time to create a repository that I can use to share reproducible bugs with you guys.
[https://github.com/eriklueth/test-backend.git](https://github.com/eriklueth/test-backend.git)

In Ticket.ts I added the extend schema but when I run the server all the queries are still generated.

I wish you a nice weekend. 😊

**Comment by a-alle** [comment] 2023-11-07 18:00
Hi @eriklueth, I am trying to reproduce your issue however I am unable to. 
The repository you linked above does not compile because it's missing the "qrcode" module. I tried creating a server using a list of the 2 type definitions from Linktree and Ticket and I'm only getting the custom Query and Mutation, no autogenerated operations. 
In order to get to the bottom of this, would you please be able to send across a minimal reproducible example?

**Comment by mjfwebb** [comment] 2024-02-05 15:26
> I reproduced the same issue. In my case the reason was that I called OGM.init() before calling the Neo4jGraphQL.getSchema(). If I change the order the issue goes away

Hi @lewisparma I can't seem to reproduce this. Do you have a small code reproduction we can use?

**Comment by angrykoala** [comment] 2024-02-27 13:12
Closing this as it is unreproducible for a while, @eriklueth  and @lewisparma  feel free to comment here if there is more information that may help us reproduce the issue

**Closed by angrykoala** 2024-02-27 13:12 UTC
Labels: bug report, unreproducible
