### ISSUE TITLE
cypherParams are not passed on to nested query 

### ISSUE THREAD

**Issue by fnfbraga** [neo4j/graphql#1249] opened 2022-04-11 08:24 UTC
**Describe the bug**
When creating a nested query which depends on cypherParams these are not readable.

`error: Expected parameter(s): cypherParams
`
This is because the `translateRead` function does not accept the `context.cypherParams`

For now we patched your package but would like to request the changes:

replace `let cypherParams = {}`
with 
`let cypherParams = context.cypherParams || {}`

 and 
`cypherParams = { ...cypherParams, ...topLevelMatch[1] }`
with
`cypherParams = { cypherParams, ...topLevelMatch[1] }`

**Comment by neo4j-team-graphql** [comment] 2022-04-11 08:24
Many thanks for raising this bug report @fnfbraga. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment] 2022-04-11 18:37
Hey @fnfbraga, it definitely sounds like there is a problem here, but can you please provide some type definitions and Query/Mutation to run to reproduce please? That way we can write tests to prevent regressions in the future. Thanks!

**Comment by fnfbraga** [comment] 2022-04-12 09:05
Hi @darrellwarde 

This essentially happens when you use `apoc.cypher.runFirstColumn` which I am not sure if its 3 or 4 levels of nesting in a query.

SO once you have the types

` 
type Level1 {
  id: ID!
  props: Level2!
}

type Level2 {
  id: ID!
  props: Level3!
}

type Level3 {
  id: ID!
  props: Level4!
  data: @cypher(
		statement: """
		  MATCH (p:Person {company: cypherParams.company})
		  RETURN p		
                 """
	)
}
`

**Comment by darrellwarde** [comment] 2022-04-12 10:08
I think possibly your reply got cut off there @fnfbraga?

**Comment by fnfbraga** [comment] 2022-04-13 11:11
> I think possibly your reply got cut off there @fnfbraga?

thank you for the heads up, updated

**Comment by fnfbraga** [comment] 2022-04-19 08:52
@darrellwarde would you like me to create a PR for this? Thank you.

**Comment by tbwiss** [comment] 2022-04-19 11:46
@fnfbraga feel free to do so!
Just keep in mind to also add a test with the example described above.
Thank you in advance!

**Comment by tbwiss** [comment] 2022-05-02 05:37
Hi @fnfbraga!
Did you consider to open a PR to address this issue? We would greatly appreciate your efforts!
Let us know, no matter if you choose so or not. Thank you in advance!

**Comment by tbwiss** [comment] 2022-05-06 05:53
@fnfbraga I tried to reproduce this error but did not succeed. I nested the query 7 levels deep. Do you happen to know another way to trigger the error?

**Comment by tbwiss** [comment] 2022-05-31 14:12
@fnfbraga since we were not able reproduce this bug. I'll therefore close this issue. If you come across a use case that we can reproduce please reopen this ticket!
Thank you!

**Comment by christian-englert-etecture** [comment] 2022-08-10 15:08
Facing same issue with nested relationship query:

Schema:
`
type Bulk @exclude(operations: [CREATE, DELETE, UPDATE]) @node(additionalLabels: ["$context.cypherParams.tenant"]) {
  id: ID!
  supplierMaterialNumber: String!
  material: Material! @relationship(type: "MATERIAL_BULK", direction: OUT)
 }
 
 type Material @exclude(operations: [CREATE, DELETE, UPDATE]) {
  id: ID!
  itemNumber: String!

  suppliers: [Supplier!]!    @relationship(type: "MATERIAL_SUPPLIER", properties: "RelationMaterialSupplier", direction: OUT)
}

type Supplier @exclude(operations: [CREATE, DELETE, UPDATE]) {
  id: ID!
  name: String
  supplierId: String!
 }

interface RelationMaterialSupplier @relationshipProperties {
  supplierMaterialNumber: String!
}
 `
 
 Query:
`
{
  bulks {
    supplierMaterialNumber
    material {
      id
      suppliersConnection {
        edges {
          supplierMaterialNumber
          node {
            supplierId
          }
        }
      }
    }
  }
}
`


Debug:
`
@neo4j/graphql:execute About to execute Cypher:
...
} RETURN suppliersConnection", { this_material: this_material, auth: $auth, **cypherParams: $cypherParams** }, false) } ]) } as this
**Params:
{
  "auth": {
    "isAuthenticated": false,
    "roles": []
  }**
} +0ms
  @neo4j/graphql:execute Neo4jError: Expected parameter(s): cypherParams

    at captureStacktrace (/home/chris/work/daimler/charmati/charmati-andockvorgang-backend/node_modules/neo4j-driver-core/lib/result.js:239:17)
    at new Result (/home/chris/work/daimler/charmati/charmati-andockvorgang-backend/node_modules/neo4j-driver-core/lib/result.js:59:23)
    at newCompletedResult (/home/chris/work/daimler/charmati/charmati-andockvorgang-backend/node_modules/neo4j-driver-core/lib/transaction.js:433:12)
    at Object.run (/home/chris/work/daimler/charmati/charmati-andockvorgang-backend/node_modules/neo4j-driver-core/lib/transaction.js:287:20)
    at Transaction.run (/home/chris/work/daimler/charmati/charmati-andockvorgang-backend/node_modules/neo4j-driver-core/lib/transaction.js:137:34)
    at Transaction.run (/home/chris/work/daimler/charmati/charmati-andockvorgang-backend/node_modules/opentelemetry-instrumentation-neo4j/src/neo4j.ts:83:60)
    at Executor.transactionRun (/home/chris/work/daimler/charmati/charmati-andockvorgang-backend/node_modules/@neo4j/graphql/src/classes/Executor.ts:215:28)
    at /home/chris/work/daimler/charmati/charmati-andockvorgang-backend/node_modules/@neo4j/graphql/src/classes/Executor.ts:196:48
    at TransactionExecutor._safeExecuteTransactionWork (/home/chris/work/daimler/charmati/charmati-andockvorgang-backend/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:92:26)
    at TransactionExecutor._executeTransactionInsidePromise (/home/chris/work/daimler/charmati/charmati-andockvorgang-backend/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:83:34) {
  constructor: [Function: Neo4jError],
  code: 'Neo.ClientError.Statement.ParameterMissing'
} +122ms
`

seems it's missing getting cypherParams from context ?
Thanks!

**Comment by christian-englert-etecture** [comment] 2022-08-10 15:10
@tbwiss : please have a look ^^ Thanks!

**Comment by neo4j-team-graphql** [comment] 2022-08-11 06:09
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @fnfbraga! :pray: We will now prioritise the bug and address it appropriately.

**Closed** 2022-08-11 13:03 UTC
Labels: confirmed, bug report, reopened
